# Generated by Django 6.1 on 2026-08-16 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_sales_stock_history'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='stock',
            name='inventory_stock_current_nonnegative',
        ),
    ]
