# Generated by Django 6.1 on 2026-08-16 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_sprint_11_5'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='stockmovement',
            name='inventory_movement_previous_nonnegative',
        ),
        migrations.RemoveConstraint(
            model_name='stockmovement',
            name='inventory_movement_final_nonnegative',
        ),
    ]
