# Generated by Django 6.1 on 2026-08-18 01:11

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_allow_negative_movement_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockmovement',
            name='nature',
            field=models.CharField(choices=[('normal', 'Normal'), ('bonus', 'Bonificada'), ('return', 'Devolucao'), ('opening_balance', 'Saldo inicial'), ('correction', 'Correcao'), ('transfer', 'Transferencia'), ('damage', 'Avaria'), ('loss', 'Perda'), ('internal_use', 'Uso interno'), ('inventory', 'Inventario'), ('regularization', 'Regularizacao'), ('balance_correction', 'Correcao de saldo'), ('sale', 'Venda'), ('consumption', 'Consumacao'), ('cancellation', 'Cancelamento/estorno'), ('other', 'Outros')], default='normal', max_length=24),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='operation_reference',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
        ),
    ]
