# Generated by Django 6.1 on 2026-08-19 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_backfill_inventory_operations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryoperation',
            name='kind',
            field=models.CharField(choices=[('manual_entry', 'Entrada manual'), ('manual_exit', 'Saída manual'), ('manual_adjustment', 'Ajuste manual'), ('group_entry', 'Entrada em grupo')], max_length=32),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='movement_type',
            field=models.CharField(choices=[('entry', 'Entrada'), ('exit', 'Saída'), ('adjustment', 'Ajuste'), ('sale', 'Venda'), ('sale_cancellation', 'Cancelamento de venda'), ('consumption', 'Consumação'), ('consumption_cancellation', 'Cancelamento de consumação')], max_length=24),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='nature',
            field=models.CharField(choices=[('normal', 'Normal'), ('bonus', 'Bonificada'), ('return', 'Devolução'), ('opening_balance', 'Saldo inicial'), ('correction', 'Correção'), ('transfer', 'Transferência'), ('damage', 'Avaria'), ('loss', 'Perda'), ('internal_use', 'Uso interno'), ('inventory', 'Inventário'), ('regularization', 'Regularização'), ('balance_correction', 'Correção de saldo'), ('sale', 'Venda'), ('consumption', 'Consumação'), ('cancellation', 'Cancelamento/estorno'), ('other', 'Outros')], default='normal', max_length=24),
        ),
    ]
