# Generated by Django 6.1 on 2026-08-23 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0029_v2_3_supplier_permissions'),
        ('inventory', '0010_alter_inventoryoperation_kind_and_more'),
        ('products', '0007_alter_product_inventory_behavior'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='average_unit_cost',
            field=models.DecimalField(blank=True, decimal_places=12, max_digits=28, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='last_unit_cost',
            field=models.DecimalField(blank=True, decimal_places=12, max_digits=28, null=True),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='nature',
            field=models.CharField(choices=[('normal', 'Normal'), ('bonus', 'Bonificada'), ('return', 'Devolução'), ('opening_balance', 'Saldo inicial'), ('correction', 'Correção'), ('transfer', 'Transferência'), ('damage', 'Avaria'), ('loss', 'Perda'), ('internal_use', 'Uso interno'), ('inventory', 'Inventário'), ('regularization', 'Regularização'), ('balance_correction', 'Correção de saldo'), ('sale', 'Venda'), ('consumption', 'Consumação'), ('cancellation', 'Cancelamento/estorno'), ('purchase', 'Compra'), ('other', 'Outros')], default='normal', max_length=24),
        ),
        migrations.AddConstraint(
            model_name='stock',
            constraint=models.CheckConstraint(condition=models.Q(('average_unit_cost__isnull', True), ('average_unit_cost__gte', 0), _connector='OR'), name='inventory_stock_average_cost_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='stock',
            constraint=models.CheckConstraint(condition=models.Q(('last_unit_cost__isnull', True), ('last_unit_cost__gte', 0), _connector='OR'), name='inventory_stock_last_cost_nonnegative'),
        ),
    ]
