# Generated by Django 6.1 on 2026-08-24 16:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commands', '0001_v2_8_commands'),
        ('inventory', '0015_v2_6_fractional_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockmovement',
            name='order_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stock_movements', to='commands.orderitem'),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='domain_origin',
            field=models.CharField(choices=[('LEGACY', 'Legado'), ('MANUAL', 'Movimentacao manual'), ('PURCHASE', 'Recebimento de compra'), ('TRANSFER_DISPATCH', 'Despacho de transferencia'), ('TRANSFER_RECEIPT', 'Recebimento de transferencia'), ('TRANSFER_RETURN', 'Retorno de transferencia'), ('TRANSFER_CORRECTION', 'Correcao de transferencia'), ('LOSS', 'Registro de perda'), ('INVENTORY_COUNT', 'Contagem de inventario'), ('ORDER', 'Confirmacao de OrderItem'), ('ORDER_CANCELLATION', 'Cancelamento de OrderItem')], default='LEGACY', editable=False, max_length=32),
        ),
    ]
