# Generated by Django 6.1 on 2026-08-25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commands', '0002_command_identifier_and_cancelled_confirmation'),
        ('inventory', '0016_v2_8_commands'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='stockmovement',
            name='inventory_movement_sales_links_coherent',
        ),
        migrations.AddConstraint(
            model_name='stockmovement',
            constraint=models.CheckConstraint(
                condition=(
                    models.Q(
                        movement_type__in=('entry', 'exit', 'adjustment'),
                        sale__isnull=True, original_movement__isnull=True,
                    )
                    | models.Q(
                        movement_type__in=('sale', 'consumption'),
                        sale__isnull=False, original_movement__isnull=True,
                    )
                    | models.Q(
                        movement_type='sale', sale__isnull=True,
                        order_item__isnull=False, original_movement__isnull=True,
                        domain_origin='ORDER',
                    )
                    | models.Q(
                        movement_type__in=('sale_cancellation', 'consumption_cancellation'),
                        sale__isnull=False, original_movement__isnull=False,
                    )
                    | models.Q(
                        movement_type='sale_cancellation', sale__isnull=True,
                        order_item__isnull=False, original_movement__isnull=False,
                        domain_origin='ORDER_CANCELLATION',
                    )
                ),
                name='inventory_movement_sales_links_coherent',
            ),
        ),
        migrations.AddConstraint(
            model_name='stockmovement',
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    order_item__isnull=False, movement_type='sale',
                    domain_origin='ORDER', original_movement__isnull=True,
                ),
                fields=('order_item', 'stock'),
                name='inventory_order_item_stock_original_unique',
            ),
        ),
    ]
