# Generated by Django 6.1 on 2026-09-11 17:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0005_table_attendance_domain'),
        ('commands', '0009_table_status_tombstone_coherence'),
        ('inventory', '0022_attendance_order_traceability'),
        ('sales', '0023_attendance_payment_provenance'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='stockmovement',
            name='inventory_movement_sales_links_coherent',
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='table_order_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stock_movements', to='attendance.tableorderitem'),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='domain_origin',
            field=models.CharField(choices=[('LEGACY', 'Legado'), ('MANUAL', 'Movimentacao manual'), ('PURCHASE', 'Recebimento de compra'), ('TRANSFER_DISPATCH', 'Despacho de transferencia'), ('TRANSFER_RECEIPT', 'Recebimento de transferencia'), ('TRANSFER_RETURN', 'Retorno de transferencia'), ('TRANSFER_CORRECTION', 'Correcao de transferencia'), ('LOSS', 'Registro de perda'), ('INVENTORY_COUNT', 'Contagem de inventario'), ('ORDER', 'Confirmacao de OrderItem'), ('ORDER_CANCELLATION', 'Cancelamento de OrderItem'), ('ATTENDANCE_ORDER', 'Confirmacao de item de atendimento'), ('ATTENDANCE_ORDER_CANCELLATION', 'Cancelamento de item de atendimento'), ('TABLE_ORDER', 'Confirmacao de item de mesa'), ('TABLE_ORDER_CANCELLATION', 'Cancelamento de item de mesa')], default='LEGACY', editable=False, max_length=32),
        ),
        migrations.AddConstraint(
            model_name='stockmovement',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('movement_type__in', ('entry', 'exit', 'adjustment')), ('original_movement__isnull', True), ('sale__isnull', True)), models.Q(('movement_type__in', ('sale', 'consumption')), ('original_movement__isnull', True), ('sale__isnull', False)), models.Q(('domain_origin', 'ORDER'), ('movement_type', 'sale'), ('order_item__isnull', False), ('original_movement__isnull', True), ('sale__isnull', True)), models.Q(('attendance_order_item__isnull', False), ('domain_origin', 'ATTENDANCE_ORDER'), ('movement_type', 'sale'), ('original_movement__isnull', True), ('sale__isnull', True)), models.Q(('domain_origin', 'TABLE_ORDER'), ('movement_type', 'sale'), ('original_movement__isnull', True), ('sale__isnull', True), ('table_order_item__isnull', False)), models.Q(('movement_type__in', ('sale_cancellation', 'consumption_cancellation')), ('original_movement__isnull', False), ('sale__isnull', False)), models.Q(('domain_origin', 'ORDER_CANCELLATION'), ('movement_type', 'sale_cancellation'), ('order_item__isnull', False), ('original_movement__isnull', False), ('sale__isnull', True)), models.Q(('attendance_order_item__isnull', False), ('domain_origin', 'ATTENDANCE_ORDER_CANCELLATION'), ('movement_type', 'sale_cancellation'), ('original_movement__isnull', False), ('sale__isnull', True)), models.Q(('domain_origin', 'TABLE_ORDER_CANCELLATION'), ('movement_type', 'sale_cancellation'), ('original_movement__isnull', False), ('sale__isnull', True), ('table_order_item__isnull', False)), _connector='OR'), name='inventory_movement_sales_links_coherent'),
        ),
        migrations.AddConstraint(
            model_name='stockmovement',
            constraint=models.UniqueConstraint(condition=models.Q(('domain_origin', 'TABLE_ORDER'), ('movement_type', 'sale'), ('original_movement__isnull', True), ('table_order_item__isnull', False)), fields=('table_order_item', 'stock'), name='inventory_table_order_item_stock_original_unique'),
        ),
    ]
