# Generated by Django 6.1 on 2026-09-14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0023_table_order_sources'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_type', models.CharField(max_length=32)),
                ('source_reference', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('ACTIVE', 'Ativa'), ('CONSUMED', 'Consumida'), ('RELEASED', 'Liberada'), ('EXPIRED', 'Expirada')], db_index=True, default='ACTIVE', max_length=10)),
                ('expires_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_reservations', to='companies.branch')),
            ],
            options={
                'ordering': ('created_at', 'pk'),
                'indexes': [models.Index(fields=['branch', 'status', 'expires_at'], name='inventory_s_branch__7f908c_idx')],
            },
        ),
        migrations.CreateModel(
            name='StockReservationRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.DecimalField(decimal_places=9, max_digits=24)),
                ('content_quantity', models.DecimalField(blank=True, decimal_places=9, max_digits=24, null=True)),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requirements', to='inventory.stockreservation')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservation_requirements', to='inventory.stock')),
            ],
            options={'ordering': ('stock_id', 'pk')},
        ),
        migrations.AddConstraint(
            model_name='stockreservation',
            constraint=models.UniqueConstraint(fields=('branch', 'source_type', 'source_reference'), name='inventory_reservation_source_unique'),
        ),
        migrations.AddConstraint(
            model_name='stockreservationrequirement',
            constraint=models.UniqueConstraint(fields=('reservation', 'stock'), name='inventory_reservation_requirement_stock_unique'),
        ),
        migrations.AddConstraint(
            model_name='stockreservationrequirement',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='inventory_reservation_requirement_quantity_positive'),
        ),
        migrations.AddConstraint(
            model_name='stockreservationrequirement',
            constraint=models.CheckConstraint(condition=models.Q(('content_quantity__isnull', True), ('content_quantity__gt', 0), _connector='OR'), name='inventory_reservation_requirement_content_positive'),
        ),
    ]
