from decimal import Decimal

from django.conf import settings
from django.db import migrations, models
from django.db.models import F, Q


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cash', '0009_remove_legacy_withdrawal_effect_constraint'),
        ('commands', '0007_report_history_snapshots'),
        ('companies', '0049_customer_identity_constraints'),
        ('sales', '0022_manual_discount_intents'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceCommand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(max_length=50)),
                ('identifier', models.CharField(blank=True, default='', max_length=100)),
                ('is_primary', models.BooleanField(default=False)),
                ('people_count', models.PositiveIntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('open', 'Aberta'), ('closed', 'Fechada')], default='open', max_length=10)),
                ('opened_by_name_snapshot', models.CharField(blank=True, default='', max_length=200)),
                ('table_name_snapshot', models.CharField(blank=True, default='', max_length=100)),
                ('customer_name_snapshot', models.CharField(blank=True, default='', max_length=200)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('closed_by_name_snapshot', models.CharField(blank=True, default='', max_length=200)),
                ('checkout_discount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('checkout_service_fee_waived', models.BooleanField(default=False)),
                ('branch', models.ForeignKey(on_delete=models.deletion.PROTECT, related_name='attendance_commands', to='companies.branch')),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=models.deletion.PROTECT, related_name='closed_attendance_commands', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=models.deletion.PROTECT, related_name='attendance_commands', to='companies.company')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=models.deletion.PROTECT, related_name='attendance_commands', to='companies.customer')),
                ('opened_by', models.ForeignKey(on_delete=models.deletion.PROTECT, related_name='opened_attendance_commands', to=settings.AUTH_USER_MODEL)),
                ('sale', models.OneToOneField(blank=True, null=True, on_delete=models.deletion.PROTECT, related_name='attendance_command', to='sales.sale')),
                ('table', models.ForeignKey(blank=True, null=True, on_delete=models.deletion.PROTECT, related_name='attendance_commands', to='commands.table')),
            ],
            options={'ordering': ('-created_at', '-id')},
        ),
        migrations.CreateModel(
            name='AttendanceOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('operation_type', models.CharField(choices=[('open_table', 'Abrir mesa'), ('transfer_command', 'Transferir comanda'), ('transfer_items', 'Transferir itens'), ('cancel_item', 'Cancelar item'), ('reverse_payment', 'Estornar pagamento')], max_length=20)),
                ('idempotency_key', models.UUIDField(editable=False)),
                ('payload_fingerprint', models.CharField(editable=False, max_length=64)),
                ('result', models.JSONField(default=dict)),
                ('branch', models.ForeignKey(on_delete=models.deletion.PROTECT, related_name='attendance_operations', to='companies.branch')),
                ('company', models.ForeignKey(on_delete=models.deletion.PROTECT, related_name='attendance_operations', to='companies.company')),
            ],
        ),
        migrations.CreateModel(
            name='AttendanceOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('draft', 'Rascunho'), ('confirmed', 'Confirmado'), ('cancelled', 'Cancelado')], default='draft', max_length=10)),
                ('command', models.ForeignKey(on_delete=models.deletion.PROTECT, related_name='orders', to='attendance.attendancecommand')),
                ('created_by', models.ForeignKey(on_delete=models.deletion.PROTECT, related_name='created_attendance_orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={'ordering': ('-created_at', '-id')},
        ),
        migrations.CreateModel(
            name='AttendanceOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=14)),
                ('product_name', models.CharField(max_length=200)),
                ('internal_code', models.CharField(blank=True, default='', max_length=100)),
                ('category_id_snapshot', models.PositiveBigIntegerField(blank=True, null=True)),
                ('category_name_snapshot', models.CharField(blank=True, default='', max_length=150)),
                ('unit', models.CharField(max_length=5)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=14)),
                ('base_unit_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('modifier_unit_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('modifier_snapshot', models.JSONField(blank=True, default=list)),
                ('notes', models.TextField(blank=True, default='')),
                ('unit_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('component_cost_snapshot', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('confirmed', 'Confirmado'), ('cancelled', 'Cancelado')], default='pending', max_length=10)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancellation_reason', models.TextField(blank=True, default='')),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=models.deletion.PROTECT, related_name='cancelled_attendance_order_items', to=settings.AUTH_USER_MODEL)),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=models.deletion.PROTECT, related_name='confirmed_attendance_order_items', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=models.deletion.PROTECT, related_name='items', to='attendance.attendanceorder')),
                ('product', models.ForeignKey(on_delete=models.deletion.PROTECT, related_name='attendance_order_items', to='products.product')),
            ],
            options={'ordering': ('id',)},
        ),
        migrations.CreateModel(
            name='AttendancePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('received_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('change_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('status', models.CharField(choices=[('applied', 'Aplicado'), ('reversed', 'Estornado')], default='applied', max_length=10)),
                ('idempotency_key', models.UUIDField(default=__import__('uuid').uuid4)),
                ('reversal_reason', models.TextField(blank=True, default='')),
                ('branch', models.ForeignKey(on_delete=models.deletion.PROTECT, related_name='attendance_payments', to='companies.branch')),
                ('cash_session', models.ForeignKey(blank=True, null=True, on_delete=models.deletion.PROTECT, related_name='attendance_payments', to='cash.cashsession')),
                ('command', models.ForeignKey(on_delete=models.deletion.PROTECT, related_name='payments', to='attendance.attendancecommand')),
                ('company', models.ForeignKey(on_delete=models.deletion.PROTECT, related_name='attendance_payments', to='companies.company')),
                ('operator', models.ForeignKey(on_delete=models.deletion.PROTECT, related_name='attendance_payments', to=settings.AUTH_USER_MODEL)),
                ('payment_method', models.ForeignKey(on_delete=models.deletion.PROTECT, related_name='attendance_payments', to='sales.paymentmethod')),
                ('reversal_of', models.OneToOneField(blank=True, null=True, on_delete=models.deletion.PROTECT, related_name='reversal', to='attendance.attendancepayment')),
            ],
            options={'ordering': ('id',)},
        ),
        migrations.AddConstraint(model_name='attendancecommand', constraint=models.UniqueConstraint(condition=Q(('status', 'open')), fields=('branch', 'number'), name='attendance_open_command_number_unique')),
        migrations.AddConstraint(model_name='attendancecommand', constraint=models.UniqueConstraint(condition=Q(('is_primary', True), ('status', 'open'), ('table__isnull', False)), fields=('table',), name='attendance_one_open_primary_per_table')),
        migrations.AddConstraint(model_name='attendancecommand', constraint=models.CheckConstraint(condition=Q(('status', 'open'), ('closed_at__isnull', False), _connector='OR'), name='attendance_closed_command_requires_timestamp')),
        migrations.AddConstraint(model_name='attendanceoperation', constraint=models.UniqueConstraint(fields=('branch', 'operation_type', 'idempotency_key'), name='attendance_operation_branch_type_idempotency_unique')),
        migrations.AddConstraint(model_name='attendanceorderitem', constraint=models.CheckConstraint(condition=Q(('quantity__gt', 0)), name='attendance_order_item_quantity_positive')),
        migrations.AddConstraint(model_name='attendanceorderitem', constraint=models.CheckConstraint(condition=Q(('unit_price__gte', 0)), name='attendance_order_item_price_nonnegative')),
        migrations.AddConstraint(model_name='attendancepayment', constraint=models.UniqueConstraint(fields=('command', 'idempotency_key'), name='attendance_payment_idempotency_unique')),
        migrations.AddConstraint(model_name='attendancepayment', constraint=models.CheckConstraint(condition=Q(('amount__gt', 0)), name='attendance_payment_amount_positive')),
        migrations.AddConstraint(model_name='attendancepayment', constraint=models.CheckConstraint(condition=Q(('received_amount__isnull', True), ('received_amount__gte', F('amount')), _connector='OR'), name='attendance_payment_received_gte_amount')),
        migrations.AddConstraint(model_name='attendancepayment', constraint=models.CheckConstraint(condition=Q(('change_amount__isnull', True), ('change_amount__gte', 0), _connector='OR'), name='attendance_payment_change_nonnegative')),
    ]
