# Generated by Django 6.1 on 2026-09-11 17:09

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_pos55_table_groups_and_bill_request'),
        ('commands', '0009_table_status_tombstone_coherence'),
        ('companies', '0051_table_manage_permission'),
        ('products', '0018_category_soft_delete_financial_overrides'),
        ('sales', '0023_attendance_payment_provenance'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TableAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('people_count', models.PositiveIntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('open', 'Aberto'), ('closed', 'Fechado')], default='open', max_length=10)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('checkout_discount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('checkout_service_fee_waived', models.BooleanField(default=False)),
                ('bill_requested_at', models.DateTimeField(blank=True, null=True)),
                ('bill_requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='requested_table_bills', to=settings.AUTH_USER_MODEL)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='table_attendances', to='companies.branch')),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='closed_table_attendances', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='table_attendances', to='companies.company')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='table_attendances', to='companies.customer')),
                ('opened_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='opened_table_attendances', to=settings.AUTH_USER_MODEL)),
                ('sale', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='table_attendance', to='sales.sale')),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='table_attendances', to='commands.table')),
            ],
            options={
                'ordering': ('-created_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='TableOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('draft', 'Rascunho'), ('confirmed', 'Confirmado'), ('cancelled', 'Cancelado')], default='draft', max_length=10)),
                ('attendance', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='attendance.tableattendance')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_table_orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='TableOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=14)),
                ('product_name', models.CharField(max_length=200)),
                ('internal_code', models.CharField(blank=True, default='', max_length=100)),
                ('category_id_snapshot', models.PositiveBigIntegerField(blank=True, null=True)),
                ('category_name_snapshot', models.CharField(blank=True, default='', max_length=150)),
                ('unit', models.CharField(max_length=5)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=14)),
                ('base_unit_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('modifier_unit_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('modifier_snapshot', models.JSONField(blank=True, default=list)),
                ('notes', models.TextField(blank=True, default='')),
                ('unit_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('component_cost_snapshot', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('confirmed', 'Confirmado'), ('cancelled', 'Cancelado')], default='pending', max_length=10)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancellation_reason', models.TextField(blank=True, default='')),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cancelled_table_order_items', to=settings.AUTH_USER_MODEL)),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='confirmed_table_order_items', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='attendance.tableorder')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='table_order_items', to='products.product')),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='TablePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('status', models.CharField(choices=[('applied', 'Aplicado'), ('reversed', 'Estornado')], default='applied', max_length=10)),
                ('idempotency_key', models.UUIDField(default=uuid.uuid4)),
                ('attendance', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='attendance.tableattendance')),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='table_payments', to=settings.AUTH_USER_MODEL)),
                ('payment_method', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='table_payments', to='sales.paymentmethod')),
            ],
        ),
        migrations.CreateModel(
            name='TablePaymentAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('person_number', models.PositiveIntegerField(blank=True, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payment_allocations', to='attendance.tableorderitem')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='allocations', to='attendance.tablepayment')),
            ],
        ),
        migrations.AddConstraint(
            model_name='tableattendance',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'open')), fields=('table',), name='table_attendance_one_open_per_table'),
        ),
        migrations.AddConstraint(
            model_name='tableattendance',
            constraint=models.CheckConstraint(condition=models.Q(('status', 'open'), ('closed_at__isnull', False), _connector='OR'), name='table_attendance_closed_requires_timestamp'),
        ),
        migrations.AddConstraint(
            model_name='tableorderitem',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='table_order_item_quantity_positive'),
        ),
        migrations.AddConstraint(
            model_name='tableorderitem',
            constraint=models.CheckConstraint(condition=models.Q(('unit_price__gte', 0)), name='table_order_item_price_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='tablepayment',
            constraint=models.UniqueConstraint(fields=('attendance', 'idempotency_key'), name='table_payment_idempotency_unique'),
        ),
        migrations.AddConstraint(
            model_name='tablepayment',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='table_payment_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='tablepaymentallocation',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='table_payment_allocation_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='tablepaymentallocation',
            constraint=models.CheckConstraint(condition=models.Q(('item__isnull', False), ('person_number__isnull', False), _connector='OR'), name='table_payment_allocation_target_required'),
        ),
    ]
