# Generated by Django 6.1 on 2026-09-11 17:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0005_table_attendance_domain'),
        ('cash', '0009_remove_legacy_withdrawal_effect_constraint'),
        ('sales', '0023_attendance_payment_provenance'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tableattendance',
            name='responsible_name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='tablepayment',
            name='cash_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='table_payments', to='cash.cashsession'),
        ),
        migrations.AddField(
            model_name='tablepayment',
            name='change_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='tablepayment',
            name='received_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='tablepayment',
            name='reversal_of',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reversal', to='attendance.tablepayment'),
        ),
        migrations.AddField(
            model_name='tablepayment',
            name='reversal_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='tablepaymentallocation',
            name='allocated_quantity',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True),
        ),
        migrations.AddConstraint(
            model_name='tablepayment',
            constraint=models.CheckConstraint(condition=models.Q(('received_amount__isnull', True), ('received_amount__gte', models.F('amount')), _connector='OR'), name='table_payment_received_gte_amount'),
        ),
        migrations.AddConstraint(
            model_name='tablepayment',
            constraint=models.CheckConstraint(condition=models.Q(('change_amount__isnull', True), ('change_amount__gte', 0), _connector='OR'), name='table_payment_change_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='tablepaymentallocation',
            constraint=models.CheckConstraint(condition=models.Q(('allocated_quantity__isnull', True), ('allocated_quantity__gt', 0), _connector='OR'), name='table_payment_allocation_quantity_positive'),
        ),
        migrations.AddConstraint(
            model_name='tablepaymentallocation',
            constraint=models.CheckConstraint(condition=models.Q(('allocated_quantity__isnull', True), ('item__isnull', False), _connector='OR'), name='table_payment_allocation_quantity_requires_item'),
        ),
    ]
