# Generated by Django 6.1 on 2026-09-13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0011_table_payment_request_fingerprint'),
    ]

    operations = [
        migrations.AddField(
            model_name='tableorderitem',
            name='financial_snapshot',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
