# Generated by Django 6.1 on 2026-09-13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0012_table_order_item_financial_snapshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='tableattendance',
            name='commission_rate_snapshot',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='tableattendance',
            name='service_fee_rate_snapshot',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
