# Generated by Django 6.1 on 2026-09-11 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0006_table_foundation_corrections'),
        ('commands', '0009_table_status_tombstone_coherence'),
        ('companies', '0051_table_manage_permission'),
        ('production', '0007_table_order_sources'),
        ('products', '0018_category_soft_delete_financial_overrides'),
        ('sales', '0023_attendance_payment_provenance'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='productionjob',
            name='production_job_exactly_one_source',
        ),
        migrations.RemoveConstraint(
            model_name='ticket',
            name='production_ticket_exactly_one_source',
        ),
        migrations.AddConstraint(
            model_name='productionjob',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('attendance_order_item__isnull', True), ('order_item__isnull', False), ('sale_item__isnull', True), ('table_order_item__isnull', True)), models.Q(('attendance_order_item__isnull', True), ('order_item__isnull', True), ('sale_item__isnull', False), ('table_order_item__isnull', True)), models.Q(('attendance_order_item__isnull', False), ('order_item__isnull', True), ('sale_item__isnull', True), ('table_order_item__isnull', True)), models.Q(('attendance_order_item__isnull', True), ('order_item__isnull', True), ('sale_item__isnull', True), ('table_order_item__isnull', False)), _connector='OR'), name='production_job_exactly_one_source'),
        ),
        migrations.AddConstraint(
            model_name='ticket',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('source_attendance_order_item__isnull', True), ('source_order_item__isnull', True), ('source_sale_item__isnull', False), ('source_table_order_item__isnull', True)), models.Q(('source_attendance_order_item__isnull', True), ('source_order_item__isnull', False), ('source_sale_item__isnull', True), ('source_table_order_item__isnull', True)), models.Q(('source_attendance_order_item__isnull', False), ('source_order_item__isnull', True), ('source_sale_item__isnull', True), ('source_table_order_item__isnull', True)), models.Q(('source_attendance_order_item__isnull', True), ('source_order_item__isnull', True), ('source_sale_item__isnull', True), ('source_table_order_item__isnull', False)), _connector='OR'), name='production_ticket_exactly_one_source'),
        ),
    ]
