PERMISSION_CATALOG = (
    ('companies.view', 'companies', 'Visualizar empresas', 'Visualizar empresas autorizadas.'),
    ('companies.change', 'companies', 'Editar empresas', 'Editar e alterar o status de empresas.'),
    ('branches.view', 'companies', 'Visualizar filiais', 'Visualizar filiais autorizadas.'),
    ('branches.add', 'companies', 'Cadastrar filiais', 'Cadastrar filiais em empresas autorizadas.'),
    ('branches.change', 'companies', 'Editar filiais', 'Editar e alterar o status de filiais.'),
    ('branches.change_settings', 'companies', 'Alterar configurações da filial', 'Alterar regras operacionais, taxa de serviço, comissão e custo fixo.'),
    ('users.view', 'accounts', 'Visualizar usuários', 'Visualizar usuários autorizados.'),
    ('users.add', 'accounts', 'Cadastrar usuários', 'Cadastrar usuários e seus acessos.'),
    ('users.change', 'accounts', 'Editar usuários', 'Editar usuários e seus acessos.'),
    ('users.change_status', 'accounts', 'Alterar status de usuários', 'Ativar e inativar usuários.'),
    ('user_permission_blocks.view', 'accounts', 'Visualizar bloqueios individuais', 'Visualizar permissões bloqueadas por usuário.'),
    ('user_permission_blocks.change', 'accounts', 'Alterar bloqueios individuais', 'Criar e revogar bloqueios individuais de permissões.'),
    ('access_profiles.view', 'accounts', 'Visualizar perfis', 'Visualizar perfis de acesso.'),
    ('access_profiles.add', 'accounts', 'Cadastrar perfis', 'Cadastrar perfis de acesso.'),
    ('access_profiles.change', 'accounts', 'Editar perfis', 'Editar perfis e permissões.'),
    ('access_profiles.change_status', 'accounts', 'Alterar status de perfis', 'Ativar e inativar perfis.'),
    ('products.view', 'products', 'Visualizar produtos', 'Visualizar o catálogo de produtos.'),
    ('products.add', 'products', 'Cadastrar produtos', 'Cadastrar produtos.'),
    ('products.change', 'products', 'Editar produtos', 'Editar produtos.'),
    ('products.change_status', 'products', 'Alterar status de produtos', 'Ativar e inativar produtos.'),
    ('products.configure_composition', 'products', 'Configurar composição', 'Configurar a composição de produtos.'),
    ('products.change_cost', 'products', 'Alterar custo de produto', 'Alterar custo cadastral de produtos.'),
    ('products.change_price', 'products', 'Alterar preço padrão', 'Alterar preço padrão de produtos.'),
    ('categories.view', 'products', 'Visualizar categorias', 'Visualizar categorias de produtos.'),
    ('categories.add', 'products', 'Cadastrar categorias', 'Cadastrar categorias de produtos.'),
    ('categories.change', 'products', 'Editar categorias', 'Editar categorias de produtos.'),
    ('categories.change_status', 'products', 'Alterar status de categorias', 'Ativar e inativar categorias.'),
    ('branch_prices.change', 'products', 'Alterar preços por filial', 'Alterar preços específicos de produtos por filial.'),
    ('inventory.view', 'inventory', 'Visualizar estoque', 'Visualizar saldos de estoque.'),
    ('inventory.move', 'inventory', 'Movimentar estoque', 'Registrar movimentações de estoque.'),
    ('inventory.entry', 'inventory', 'Registrar entrada', 'Registrar entradas individuais ou em grupo.'),
    ('inventory.exit', 'inventory', 'Registrar saída', 'Registrar saídas de estoque.'),
    ('inventory.adjust', 'inventory', 'Ajustar estoque', 'Registrar inventário e correção de saldo.'),
    ('inventory.regularize', 'inventory', 'Regularizar negativos', 'Regularizar explicitamente saldos negativos.'),
    ('inventory.change_minimum', 'inventory', 'Alterar estoque mínimo', 'Configurar estoque mínimo.'),
    ('inventory.view_history', 'inventory', 'Visualizar histórico', 'Visualizar histórico de estoque.'),
    ('inventory.view_stock_kpis', 'inventory', 'Visualizar indicadores de estoque', 'Visualizar indicadores de estoque baixo e zerado.'),
    ('inventory.view_stock_costs', 'inventory', 'Visualizar custos de estoque', 'Visualizar custos e valor estimado do estoque.'),
    ('cash_registers.view', 'cash_registers', 'Visualizar caixas', 'Visualizar caixas.'),
    ('cash_registers.open', 'cash_registers', 'Abrir caixa', 'Abrir caixas.'),
    ('cash_registers.manual_entry', 'cash_registers', 'Realizar entrada manual', 'Registrar entradas manuais no caixa.'),
    ('cash_registers.withdraw', 'cash_registers', 'Realizar sangria', 'Registrar sangrias no caixa.'),
    ('cash_registers.close', 'cash_registers', 'Fechar caixa', 'Fechar caixas.'),
    ('cash_registers.add', 'cash_registers', 'Cadastrar caixa', 'Cadastrar caixas na filial.'),
    ('cash_registers.change', 'cash_registers', 'Editar caixa', 'Editar caixas da filial.'),
    ('cash_registers.change_status', 'cash_registers', 'Alterar status de caixa', 'Ativar e inativar caixas.'),
    ('cash_registers.administer_others', 'cash_registers', 'Administrar caixas de outros', 'Operar sessões abertas por outros usuários.'),
    ('sales.create', 'sales', 'Realizar vendas', 'Registrar vendas.'),
    ('sales.view', 'sales', 'Visualizar vendas', 'Visualizar vendas.'),
    ('sales.cancel', 'sales', 'Cancelar vendas', 'Cancelar vendas.'),
    ('sales.apply_discount', 'sales', 'Aplicar desconto', 'Aplicar descontos em vendas.'),
    ('sales.apply_item_discount', 'sales', 'Aplicar desconto por item', 'Aplicar desconto manual em itens de venda, independente do desconto na conta.'),
    ('sales.waive_service_fee', 'sales', 'Retirar taxa de serviço', 'Retirar taxa de serviço com permissão ou autorização pontual.'),
    ('sales.create_consumption', 'sales', 'Criar consumação', 'Criar consumações.'),
    ('sales.view_consumption', 'sales', 'Visualizar consumação', 'Visualizar consumações.'),
    ('sales.cancel_consumption', 'sales', 'Cancelar consumação', 'Cancelar consumações.'),
    ('payment_methods.view', 'payment_methods', 'Visualizar formas de pagamento', 'Visualizar formas de pagamento.'),
    ('payment_methods.change', 'payment_methods', 'Configurar formas de pagamento', 'Configurar formas de pagamento.'),
    ('promotions.view', 'promotions', 'Visualizar promoções', 'Visualizar promoções.'),
    ('promotions.change', 'promotions', 'Configurar promoções', 'Criar, editar e alterar o status de promoções.'),
    ('dashboard.view', 'reports', 'Visualizar Dashboard', 'Visualizar indicadores executivos autorizados.'),
    ('reports.view_sales', 'reports', 'Visualizar relatório de vendas', 'Visualizar relatório operacional de vendas.'),
    ('reports.view_consumptions', 'reports', 'Visualizar relatório de consumações', 'Visualizar relatório operacional de consumações.'),
    ('reports.view_cash', 'reports', 'Visualizar relatório de caixa', 'Visualizar relatório operacional de caixa.'),
    ('reports.view_withdrawals', 'reports', 'Visualizar relatório de sangrias', 'Visualizar relatório operacional de sangrias.'),
    ('reports.view_inventory', 'reports', 'Visualizar relatório de estoque', 'Visualizar relatório de movimentações de estoque.'),
    ('reports.view_operational_result', 'reports', 'Visualizar resultado operacional', 'Visualizar resultado operacional estimado da filial.'),
    ('reports.view_stock_consumption', 'reports', 'Visualizar consumo físico', 'Visualizar produtos e insumos consumidos.'),
    ('reports.view_products', 'reports', 'Visualizar performance de produtos', 'Visualizar produtos e categorias vendidos.'),
    ('reports.view_receipts', 'reports', 'Visualizar recebimentos', 'Visualizar recebimentos por forma de pagamento.'),
    ('reports.view_team', 'reports', 'Visualizar equipe', 'Visualizar desempenho de operadores e atendentes.'),
    ('reports.view_discounts', 'reports', 'Visualizar descontos', 'Visualizar descontos manuais e promocionais.'),
    ('reports.view_cancellations', 'reports', 'Visualizar cancelamentos', 'Visualizar cancelamentos e estornos.'),
    ('reports.view_prices', 'reports', 'Visualizar preços', 'Visualizar comparativo de preços por filial.'),
    ('reports.export', 'reports', 'Exportar relatórios', 'Exportar relatórios operacionais.'),
    ('audit_logs.view', 'audit_logs', 'Visualizar auditoria', 'Consultar logs de auditoria.'),
    ('commissions.view', 'commissions', 'Visualizar comissões', 'Visualizar valores e relatórios de comissão.'),
    ('commissions.change_branch_default', 'commissions', 'Alterar comissão da filial', 'Alterar percentual padrão de comissão da filial.'),
    ('commissions.change_profile', 'commissions', 'Alterar comissão do perfil', 'Alterar regra de comissão em perfis de acesso.'),
    ('commissions.change_user_override', 'commissions', 'Alterar comissão individual', 'Alterar configuração individual de comissão por usuário.'),
)

ALL_PERMISSION_CODES = frozenset(item[0] for item in PERMISSION_CATALOG)

OPERATING_PERMISSION_CODES = frozenset(
    code
    for code in ALL_PERMISSION_CODES
    if (
        code.split('.', 1)[0]
        in {'products', 'categories', 'inventory', 'cash_registers', 'sales', 'payment_methods', 'promotions', 'reports', 'dashboard', 'branch_prices', 'audit_logs'}
        or code in {
            'commissions.view',
            'commissions.change_branch_default',
            'commissions.change_user_override',
        }
    )
)

DEFAULT_PROFILE_PERMISSIONS = {
    'Administrador': ALL_PERMISSION_CODES,
    'Gerente': frozenset(
        {
            'companies.view', 'branches.view', 'products.view', 'categories.view',
            'inventory.view',
            'inventory.move', 'inventory.entry', 'inventory.exit', 'inventory.adjust',
            'inventory.regularize', 'inventory.change_minimum', 'inventory.view_history',
            'inventory.view_stock_kpis', 'inventory.view_stock_costs', 'cash_registers.view',
            'cash_registers.open', 'cash_registers.manual_entry', 'cash_registers.withdraw',
            'cash_registers.close', 'sales.create', 'sales.view', 'sales.cancel',
            'sales.apply_discount', 'sales.waive_service_fee', 'sales.create_consumption',
            'sales.view_consumption', 'sales.cancel_consumption', 'payment_methods.view',
            'promotions.view', 'dashboard.view',
            'reports.view_sales', 'reports.view_consumptions', 'reports.view_cash',
            'reports.view_withdrawals', 'reports.view_inventory',
            'reports.view_operational_result', 'reports.view_stock_consumption',
            'reports.view_products', 'reports.view_receipts', 'reports.view_team',
            'reports.view_discounts', 'reports.view_cancellations', 'reports.view_prices',
            'reports.export', 'commissions.view',
        }
    ),
    'Operador de Caixa': frozenset(
        {
            'companies.view',
            'branches.view',
            'products.view',
            'inventory.view',
            'cash_registers.view',
            'cash_registers.open',
            'cash_registers.manual_entry',
            'cash_registers.withdraw',
            'cash_registers.close',
            'sales.create',
            'sales.view',
            'sales.create_consumption',
            'sales.view_consumption',
            'payment_methods.view',
            'promotions.view',
            'reports.view_sales',
            'reports.view_consumptions',
            'reports.view_cash',
            'reports.view_withdrawals',
            'sales.waive_service_fee',
        }
    ),
    'Operador de Estoque': frozenset(
        {
            'companies.view',
            'branches.view',
            'products.view',
            'products.add',
            'products.change',
            'products.change_status',
            'products.configure_composition',
            'inventory.view',
            'inventory.move',
            'inventory.entry',
            'inventory.exit',
            'inventory.adjust',
            'inventory.regularize',
            'inventory.change_minimum',
            'inventory.view_history',
            'inventory.view_stock_kpis',
            'reports.view_inventory',
        }
    ),
}

DEFAULT_PROFILE_DESCRIPTIONS = {
    'Administrador': 'Acesso completo a empresa.',
    'Gerente': 'Acesso gerencial operacional sem capacidades sensiveis de seguranca.',
    'Operador de Caixa': 'Acesso a caixa, vendas e consultas operacionais.',
    'Operador de Estoque': 'Acesso ao catalogo de produtos e estoque.',
}
