# Generated by Django 6.1 on 2026-08-23 23:00

import django.db.models.deletion
import django.db.models.expressions
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0029_v2_3_supplier_permissions'),
        ('products', '0007_alter_product_inventory_behavior'),
        ('suppliers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order_number', models.CharField(max_length=20)),
                ('order_type', models.CharField(choices=[('ORDER', 'Pedido de compra'), ('DIRECT', 'Entrada direta')], max_length=10)),
                ('status', models.CharField(choices=[('DRAFT', 'Rascunho'), ('PLACED', 'Realizado'), ('PARTIALLY_RECEIVED', 'Recebido parcialmente'), ('RECEIVED', 'Recebido'), ('CANCELLED', 'Cancelado'), ('CLOSED_PARTIAL', 'Parcial encerrado')], default='DRAFT', max_length=24)),
                ('gross_total', models.DecimalField(decimal_places=2, max_digits=16)),
                ('global_discount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=16)),
                ('freight_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=16)),
                ('other_expenses_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=16)),
                ('payable_total', models.DecimalField(decimal_places=2, max_digits=16)),
                ('document_number', models.CharField(blank=True, max_length=100)),
                ('document_key', models.CharField(blank=True, max_length=100)),
                ('document_series', models.CharField(blank=True, max_length=30)),
                ('document_date', models.DateField(blank=True, null=True)),
                ('attachment_reference', models.CharField(blank=True, max_length=500)),
                ('notes', models.TextField(blank=True)),
                ('placed_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('closure_reason', models.TextField(blank=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders', to='companies.branch')),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='closed_purchase_orders', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders', to='companies.company')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_purchase_orders', to=settings.AUTH_USER_MODEL)),
                ('placed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='placed_purchase_orders', to=settings.AUTH_USER_MODEL)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders', to='suppliers.supplier')),
            ],
            options={
                'ordering': ('-created_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='PayableInstallment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('installment_number', models.PositiveIntegerField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=16)),
                ('due_date', models.DateField()),
                ('status', models.CharField(choices=[('PENDING', 'Pendente'), ('PAID', 'Paga'), ('CANCELLED', 'Cancelada')], default='PENDING', max_length=10)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancellation_reason', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cancelled_purchase_installments', to=settings.AUTH_USER_MODEL)),
                ('paid_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='paid_purchase_installments', to=settings.AUTH_USER_MODEL)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_installments', to='suppliers.supplier')),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='installments', to='purchases.purchaseorder')),
            ],
            options={
                'ordering': ('due_date', 'installment_number', 'id'),
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('line_number', models.PositiveIntegerField()),
                ('ordered_quantity', models.DecimalField(decimal_places=6, max_digits=18)),
                ('product_name', models.CharField(max_length=200)),
                ('product_internal_code', models.CharField(max_length=100)),
                ('product_stock_unit', models.CharField(max_length=5)),
                ('supplier_name', models.CharField(max_length=200)),
                ('supplier_tax_id', models.CharField(blank=True, max_length=14)),
                ('supplier_product_code', models.CharField(blank=True, max_length=100)),
                ('presentation_unit_code', models.CharField(max_length=20)),
                ('presentation_description', models.CharField(max_length=200)),
                ('conversion_factor', models.DecimalField(decimal_places=6, max_digits=18)),
                ('purchase_unit_price', models.DecimalField(decimal_places=6, max_digits=18)),
                ('gross_subtotal', models.DecimalField(decimal_places=2, max_digits=16)),
                ('allocated_discount', models.DecimalField(decimal_places=2, max_digits=16)),
                ('allocated_freight', models.DecimalField(decimal_places=2, max_digits=16)),
                ('allocated_other_expenses', models.DecimalField(decimal_places=2, max_digits=16)),
                ('effective_total', models.DecimalField(decimal_places=2, max_digits=16)),
                ('effective_stock_unit_cost', models.DecimalField(decimal_places=12, max_digits=28)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_order_items', to='products.product')),
                ('product_supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_order_items', to='suppliers.productsupplier')),
                ('product_supplier_unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_order_items', to='suppliers.productsupplierunit')),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='purchases.purchaseorder')),
            ],
            options={
                'ordering': ('line_number', 'id'),
            },
        ),
        migrations.CreateModel(
            name='PurchaseReceipt',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('idempotency_key', models.UUIDField(editable=False)),
                ('payload_fingerprint', models.CharField(editable=False, max_length=64)),
                ('payload', models.JSONField(default=dict, editable=False)),
                ('notes', models.TextField(blank=True)),
                ('divergence_reason', models.TextField(blank=True)),
                ('confirmed_at', models.DateTimeField()),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_receipts', to='companies.branch')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_receipts', to='companies.company')),
                ('confirmed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='confirmed_purchase_receipts', to=settings.AUTH_USER_MODEL)),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receipts', to='purchases.purchaseorder')),
            ],
            options={
                'ordering': ('-confirmed_at', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='PurchaseReceiptItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ordered_quantity_snapshot', models.DecimalField(decimal_places=6, max_digits=18)),
                ('previously_received_quantity', models.DecimalField(decimal_places=6, max_digits=18)),
                ('received_quantity', models.DecimalField(decimal_places=6, max_digits=18)),
                ('accumulated_quantity', models.DecimalField(decimal_places=6, max_digits=18)),
                ('pending_quantity', models.DecimalField(decimal_places=6, max_digits=18)),
                ('divergence_quantity', models.DecimalField(decimal_places=6, max_digits=18)),
                ('divergence_reason', models.TextField(blank=True)),
                ('conversion_factor_snapshot', models.DecimalField(decimal_places=6, max_digits=18)),
                ('stock_quantity', models.DecimalField(decimal_places=6, max_digits=18)),
                ('effective_stock_unit_cost_snapshot', models.DecimalField(decimal_places=12, max_digits=28)),
                ('product_name_snapshot', models.CharField(max_length=200)),
                ('supplier_name_snapshot', models.CharField(max_length=200)),
                ('presentation_snapshot', models.CharField(max_length=200)),
                ('purchase_order_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receipt_items', to='purchases.purchaseorderitem')),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='purchases.purchasereceipt')),
            ],
            options={
                'ordering': ('purchase_order_item__line_number', 'id'),
            },
        ),
        migrations.AddConstraint(
            model_name='purchaseorder',
            constraint=models.UniqueConstraint(fields=('company', 'order_number'), name='purchases_order_company_number_unique'),
        ),
        migrations.AddConstraint(
            model_name='purchaseorder',
            constraint=models.CheckConstraint(condition=models.Q(('gross_total__gte', 0), ('global_discount__gte', 0), ('global_discount__lte', models.F('gross_total')), ('freight_total__gte', 0), ('other_expenses_total__gte', 0), ('payable_total__gte', 0)), name='purchases_order_amounts_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='purchaseorder',
            constraint=models.CheckConstraint(condition=models.Q(('payable_total', django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(models.F('gross_total'), '-', models.F('global_discount')), '+', models.F('freight_total')), '+', models.F('other_expenses_total')))), name='purchases_order_payable_total_coherent'),
        ),
        migrations.AddConstraint(
            model_name='payableinstallment',
            constraint=models.UniqueConstraint(fields=('purchase_order', 'installment_number'), name='purchases_installment_number_unique'),
        ),
        migrations.AddConstraint(
            model_name='payableinstallment',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='purchases_installment_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='payableinstallment',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('cancellation_reason', ''), ('cancelled_at__isnull', True), ('cancelled_by__isnull', True), ('paid_at__isnull', True), ('paid_by__isnull', True), ('status', 'PENDING')), models.Q(('cancellation_reason', ''), ('cancelled_at__isnull', True), ('cancelled_by__isnull', True), ('paid_at__isnull', False), ('paid_by__isnull', False), ('status', 'PAID')), models.Q(('cancelled_at__isnull', False), ('cancelled_by__isnull', False), ('paid_at__isnull', True), ('paid_by__isnull', True), ('status', 'CANCELLED')), _connector='OR'), name='purchases_installment_status_coherent'),
        ),
        migrations.AddConstraint(
            model_name='purchaseorderitem',
            constraint=models.UniqueConstraint(fields=('purchase_order', 'line_number'), name='purchases_order_item_line_unique'),
        ),
        migrations.AddConstraint(
            model_name='purchaseorderitem',
            constraint=models.CheckConstraint(condition=models.Q(('ordered_quantity__gt', 0), ('conversion_factor__gt', 0), ('purchase_unit_price__gte', 0), ('gross_subtotal__gte', 0), ('allocated_discount__gte', 0), ('allocated_freight__gte', 0), ('allocated_other_expenses__gte', 0), ('effective_total__gte', 0), ('effective_stock_unit_cost__gte', 0)), name='purchases_order_item_amounts_valid'),
        ),
        migrations.AddConstraint(
            model_name='purchasereceipt',
            constraint=models.UniqueConstraint(fields=('branch', 'idempotency_key'), name='purchases_receipt_branch_idempotency_unique'),
        ),
        migrations.AddConstraint(
            model_name='purchasereceiptitem',
            constraint=models.UniqueConstraint(fields=('receipt', 'purchase_order_item'), name='purchases_receipt_item_unique'),
        ),
        migrations.AddConstraint(
            model_name='purchasereceiptitem',
            constraint=models.CheckConstraint(condition=models.Q(('ordered_quantity_snapshot__gt', 0), ('previously_received_quantity__gte', 0), ('received_quantity__gt', 0), ('accumulated_quantity__gt', 0), ('pending_quantity__gte', 0), ('conversion_factor_snapshot__gt', 0), ('stock_quantity__gt', 0), ('effective_stock_unit_cost_snapshot__gte', 0)), name='purchases_receipt_item_quantities_valid'),
        ),
    ]
