# Generated by Django 6.1 on 2026-08-23 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='purchasereceiptitem',
            name='purchases_receipt_item_quantities_valid',
        ),
        migrations.AddConstraint(
            model_name='purchasereceiptitem',
            constraint=models.CheckConstraint(condition=models.Q(('ordered_quantity_snapshot__gt', 0), ('previously_received_quantity__gte', 0), ('received_quantity__gte', 0), ('accumulated_quantity__gte', 0), ('pending_quantity__gte', 0), ('conversion_factor_snapshot__gt', 0), ('stock_quantity__gte', 0), ('effective_stock_unit_cost_snapshot__gte', 0)), name='purchases_receipt_item_quantities_valid'),
        ),
    ]
