# Generated by Django 6.1 on 2026-08-24 23:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0004_v2_6_purchase_content'),
        ('suppliers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorderitem',
            name='product_supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchase_order_items', to='suppliers.productsupplier'),
        ),
        migrations.AlterField(
            model_name='purchaseorderitem',
            name='product_supplier_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchase_order_items', to='suppliers.productsupplierunit'),
        ),
    ]
