# Generated by Django 6.1 on 2026-08-26

from django.db import migrations, models
from django.db.models import F, Q


def prepare_existing_payments_and_check_due_dates(apps, schema_editor):
    PayableInstallment = apps.get_model('purchases', 'PayableInstallment')
    duplicates = (
        PayableInstallment.objects.values('purchase_order_id', 'due_date')
        .annotate(total=models.Count('id')).filter(total__gt=1)
    )
    if duplicates.exists():
        raise RuntimeError(
            'Existem parcelas com vencimento duplicado na mesma compra; '
            'corrija os dados antes de aplicar a restrição de vencimento único.'
        )
    PayableInstallment.objects.filter(status='PAID').update(
        paid_amount=F('amount'), paid_payment_method='MANUAL',
    )


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0005_v2_10_optional_supplier_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='payableinstallment',
            name='paid_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True),
        ),
        migrations.AddField(
            model_name='payableinstallment',
            name='paid_payment_method',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.RunPython(
            prepare_existing_payments_and_check_due_dates,
            migrations.RunPython.noop,
        ),
        migrations.RemoveConstraint(
            model_name='payableinstallment',
            name='purchases_installment_status_coherent',
        ),
        migrations.AddConstraint(
            model_name='payableinstallment',
            constraint=models.UniqueConstraint(
                fields=('purchase_order', 'due_date'),
                name='purchases_installment_due_date_unique',
            ),
        ),
        migrations.AddConstraint(
            model_name='payableinstallment',
            constraint=models.CheckConstraint(
                condition=(
                    Q(
                        status='PENDING', paid_at__isnull=True,
                        paid_amount__isnull=True, paid_payment_method='',
                        paid_by__isnull=True, cancelled_at__isnull=True,
                        cancelled_by__isnull=True, cancellation_reason='',
                    )
                    | Q(
                        status='PAID', paid_at__isnull=False,
                        paid_amount__isnull=False, paid_payment_method__gt='',
                        paid_by__isnull=False, cancelled_at__isnull=True,
                        cancelled_by__isnull=True, cancellation_reason='',
                    )
                    | Q(
                        status='CANCELLED', paid_at__isnull=True,
                        paid_amount__isnull=True, paid_payment_method='',
                        paid_by__isnull=True, cancelled_at__isnull=False,
                        cancelled_by__isnull=False,
                    )
                ),
                name='purchases_installment_status_coherent',
            ),
        ),
    ]
