import type { Metadata } from "next";
import Link from "next/link";
import { ArrowRight } from "lucide-react";
import { PublicFooter } from "@/components/marketing/public-footer";
import { PublicHeader } from "@/components/marketing/public-header";
import { PaymentDevices, ProductEvidence, VideoTeaser } from "@/components/marketing/product-evidence";

export const metadata: Metadata = { title: "Core Pdv", description: "Conecte vendas, caixa, estoque, mesas, compras, pagamentos e gestão em uma única plataforma." };

const structuredData = { "@context": "https://schema.org", "@type": "SoftwareApplication", name: "CORE PDV", applicationCategory: "BusinessApplication", operatingSystem: "Web", description: "Plataforma para conectar operações de ponto de venda e gestão." };
const flow = ["Venda", "Pagamento", "Caixa", "Estoque", "Gestão"];
const posItems = ["Venda rápida", "Operadores e atendimento", "Mesas, comandas e pedidos", "Caixa, pagamentos e impressão"];
const backofficeItems = ["Produtos, preços e estoque", "Compras e fornecedores", "Relatórios e financeiro", "Filiais, usuários e permissões"];

export default function HomePage() {
  const hasTeaser = Boolean(process.env.NEXT_PUBLIC_CORE_TEASER_URL);
  return <div className="min-h-screen bg-canvas text-fg"><PublicHeader active="home" /><main><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(structuredData) }} />
    <section className="border-b border-subtle bg-surface"><div className="mx-auto grid max-w-7xl gap-10 px-4 py-16 sm:px-6 sm:py-24 lg:grid-cols-[0.9fr_1.1fr] lg:items-center lg:px-8"><div className="max-w-3xl"><p className="marketing-eyebrow">CORE PDV</p><h1 className="mt-5 text-4xl font-black leading-[1.03] tracking-[-0.055em] text-fg sm:text-6xl">Sua operação inteira. Conectada pelo CORE.</h1><p className="mt-6 max-w-2xl text-base leading-8 text-muted">PDV, pagamentos, mesas, estoque, compras, financeiro e gestão para operações presenciais que precisam seguir em movimento.</p><div className="mt-8 flex flex-col gap-3 sm:flex-row"><Link href="/contato" className="inline-flex h-12 items-center justify-center gap-2 rounded-xl bg-primary px-6 text-sm font-bold text-white transition hover:bg-primary-dark">Solicitar demonstração <ArrowRight className="size-4" /></Link>{hasTeaser && <Link href="#em-acao" className="inline-flex h-12 items-center justify-center gap-2 rounded-xl border border-subtle px-6 text-sm font-bold text-fg transition hover:bg-surface-muted">Ver o CORE em ação <ArrowRight className="size-4" /></Link>}</div></div><ProductEvidence title="" src="/site/images/hero-operation.webp" alt="CORE POS em uma operação presencial" priority className="shadow-[18px_18px_0_#3454d1]" /></div></section>

    <section className="border-b border-subtle bg-canvas"><div className="mx-auto max-w-7xl px-4 py-16 sm:px-6 lg:px-8"><div className="max-w-2xl"><p className="marketing-eyebrow">Informação conectada</p><h2 className="mt-4 text-3xl font-black tracking-[-0.045em] text-fg">O que acontece na operação continua na gestão.</h2></div><div className="mt-10 grid gap-0 border-y border-subtle md:grid-cols-5">{flow.map((item, index) => <div key={item} className="relative border-b border-subtle px-4 py-6 last:border-b-0 md:border-b-0 md:border-r md:last:border-r-0"><span className="text-[11px] font-bold tracking-[0.16em] text-primary">0{index + 1}</span><p className="mt-8 text-xl font-black tracking-tight text-fg">{item}</p>{index < flow.length - 1 && <span className="absolute bottom-0 left-4 right-4 h-px bg-primary/45 md:bottom-auto md:left-auto md:right-[-1px] md:top-1/2 md:h-9 md:w-px" aria-hidden="true" />}</div>)}</div></div></section>

    {hasTeaser && <section id="em-acao" className="scroll-mt-20"><div className="mx-auto max-w-7xl px-4 py-18 sm:px-6 sm:py-24 lg:px-8"><div className="mb-8 max-w-2xl"><p className="marketing-eyebrow">CORE em operação</p><h2 className="mt-4 text-3xl font-black tracking-[-0.045em] text-fg sm:text-4xl">Veja o CORE em operação.</h2></div><VideoTeaser /></div></section>}

    <section className="border-y border-subtle bg-surface"><div className="mx-auto grid max-w-7xl gap-10 px-4 py-18 sm:px-6 sm:py-24 lg:grid-cols-2 lg:px-8"><div><div className="flex items-baseline gap-4"><span className="text-5xl font-black tracking-[-0.08em] text-primary/20">01</span><p className="marketing-eyebrow">CORE POS</p></div><h2 className="mt-4 text-3xl font-black tracking-[-0.045em] text-fg">A operação acontece aqui.</h2><p className="mt-5 text-sm leading-7 text-muted">O CORE POS reúne os fluxos que acontecem no balcão, no salão e no caixa. A equipe atende, registra e encerra a rotina operacional no próprio ponto de venda.</p><ul className="mt-7 grid gap-3 border-t border-subtle pt-6 text-sm font-semibold text-fg sm:grid-cols-2">{posItems.map((item) => <li key={item}>{item}</li>)}</ul></div><ProductEvidence title="CORE POS" description="Venda e pagamento no ritmo da operação." src="/site/screenshots/core-pos-venda.webp" alt="Tela real do CORE POS na venda rápida" /></div></section>

    <section><div className="mx-auto grid max-w-7xl gap-10 px-4 py-18 sm:px-6 sm:py-24 lg:grid-cols-2 lg:px-8"><ProductEvidence title="Gestão do negócio" description="Acompanhe vendas, estoque e resultados em um só lugar." src="/site/screenshots/backoffice-dashboard.webp" alt="Tela real do Gestão do negócio" /><div><div className="flex items-baseline gap-4"><span className="text-5xl font-black tracking-[-0.08em] text-primary/20">02</span><p className="marketing-eyebrow">Gestão do negócio</p></div><h2 className="mt-4 text-3xl font-black tracking-[-0.045em] text-fg">A gestão acontece aqui.</h2><p className="mt-5 text-sm leading-7 text-muted">Produtos, estoque, compras, relatórios, financeiro e acessos compõem o ambiente de acompanhamento e controle da empresa.</p><ul className="mt-7 grid gap-3 border-t border-subtle pt-6 text-sm font-semibold text-fg sm:grid-cols-2">{backofficeItems.map((item) => <li key={item}>{item}</li>)}</ul></div></div></section>

    <section id="integracoes" className="border-y border-subtle bg-surface"><div className="mx-auto max-w-7xl px-4 py-18 sm:px-6 sm:py-24 lg:px-8"><div className="grid gap-8 lg:grid-cols-[0.85fr_1.15fr] lg:items-end"><div><p className="marketing-eyebrow">Pagamentos</p><h2 className="mt-4 text-3xl font-black tracking-[-0.045em] text-fg">Venda e receba no mesmo lugar.</h2></div><p className="max-w-xl text-sm leading-7 text-muted">Atenda no balcão ou na mesa e receba pela maquininha, com o pagamento ligado à venda.</p></div><PaymentDevices /><Link href="/solucoes#pagamentos" className="mt-8 inline-flex items-center gap-2 text-sm font-bold text-primary hover:text-primary-dark">Ver como funciona <ArrowRight className="size-4" /></Link></div></section>

    <section id="segmentos"><div className="mx-auto grid max-w-7xl gap-10 px-4 py-18 sm:px-6 sm:py-24 lg:grid-cols-[0.8fr_1.2fr] lg:px-8"><div><p className="marketing-eyebrow">Segmentos</p><h2 className="mt-4 text-3xl font-black tracking-[-0.045em] text-fg">Operações presenciais, cada uma com sua rotina.</h2><p className="mt-5 text-sm leading-7 text-muted">Bares, restaurantes, lounges, casas de eventos, pizzarias, lanchonetes, food service, varejo e outras operações compatíveis.</p></div><ProductEvidence title="" src="/site/images/segments-operation.webp" alt="Atendimento em uma operação presencial" /></div></section>

    <section id="seguranca" className="border-y border-subtle bg-surface"><div className="mx-auto grid max-w-7xl gap-10 px-4 py-18 sm:px-6 sm:py-24 lg:grid-cols-2 lg:px-8"><ProductEvidence title="Controle da equipe" description="Veja quem acessou o sistema e o que foi feito." src="/site/screenshots/auditoria.webp" alt="Histórico de ações da equipe no sistema" /><div><p className="marketing-eyebrow">Segurança e controle</p><h2 className="mt-4 text-3xl font-black tracking-[-0.045em] text-fg">Saiba quem fez cada ação no seu negócio.</h2><p className="mt-5 text-sm leading-7 text-muted">Defina o que cada funcionário pode acessar e acompanhe o histórico de ações em cada loja.</p></div></div></section>

    <section className="bg-canvas"><div className="mx-auto grid max-w-7xl gap-8 px-4 py-18 sm:px-6 sm:py-24 lg:grid-cols-[1fr_auto] lg:items-end lg:px-8"><div><p className="marketing-eyebrow">Vamos conversar</p><h2 className="mt-4 max-w-2xl text-3xl font-black tracking-[-0.045em] text-fg sm:text-4xl">Conheça o CORE a partir da sua operação.</h2><p className="mt-5 max-w-xl text-sm leading-7 text-muted">A equipe CORE entende o seu cenário antes da próxima etapa.</p></div><Link href="/contato" className="inline-flex h-12 items-center justify-center gap-2 rounded-xl bg-primary px-6 text-sm font-bold text-white transition hover:bg-primary-dark">Solicitar demonstração <ArrowRight className="size-4" /></Link></div></section>
  </main><PublicFooter /></div>;
}
