"use client"

import { useState } from "react"
import { BarChart3, ChevronDown, Download, Filter, FileSpreadsheet, FileText, MoreHorizontal, Package, ShoppingCart, WalletCards, X } from "lucide-react"

const tabs = ["Resumo", "Vendas", "Itens", "Pagamentos", "Vendas por hora"]
const sales = [
  ["V00047", "Hoje, 14:32", "Ana Souza", "Dinheiro", "Concluída", "R$ 248,90"],
  ["V00046", "Hoje, 13:18", "Carlos Lima", "Pix", "Concluída", "R$ 186,40"],
  ["V00045", "Hoje, 11:06", "Marina Alves", "Cartão", "Concluída", "R$ 412,80"],
  ["V00044", "Ontem, 18:51", "João Mendes", "Pix", "Cancelada", "R$ 97,50"],
]
const items = [["Café especial 250g", "Alimentos", "86", "R$ 2.451,20"], ["Leite integral 1L", "Laticínios", "72", "R$ 431,28"], ["Pão artesanal", "Padaria", "58", "R$ 812,00"], ["Suco natural 500ml", "Bebidas", "41", "R$ 492,00"]]
const payments = [["Pix", "48", "R$ 4.862,40", "51,8%"], ["Cartão de crédito", "29", "R$ 3.184,70", "33,9%"], ["Dinheiro", "14", "R$ 1.020,60", "10,9%"], ["Débito", "7", "R$ 318,40", "3,4%"]]

function Card({ children, className = "" }: { children: React.ReactNode; className?: string }) { return <section className={`rounded-2xl border border-subtle bg-surface shadow-[0_10px_30px_rgba(40,60,80,0.05)] ${className}`}>{children}</section> }
function MiniChart() { return <div className="flex h-44 items-end gap-2 border-b border-subtle px-2 pb-2 pt-5">{[42,58,48,71,66,88,77,96,74,82,100,91].map((h, i) => <div key={i} className="group flex flex-1 flex-col items-center gap-2"><div className="w-full rounded-t-md bg-primary/80 transition group-hover:bg-primary" style={{ height: `${h}%` }} /><span className="text-[10px] text-muted">{i + 8}h</span></div>)}</div> }
function Donut() { return <div className="relative grid size-36 place-items-center rounded-full" style={{ background: "conic-gradient(var(--brand-primary) 0 52%, #0e7490 52% 86%, #17c666 86% 97%, #ffa21d 97% 100%)" }}><div className="grid size-24 place-items-center rounded-full bg-surface text-center"><strong className="text-xl">R$ 9,3k</strong><span className="text-[10px] text-muted">recebido</span></div></div> }
function Table({ headers, rows }: { headers: string[]; rows: string[][] }) { return <div className="overflow-x-auto"><table className="w-full min-w-[640px] text-left text-sm"><thead className="bg-surface-muted text-[10px] uppercase tracking-[.12em] text-muted"><tr>{headers.map(h => <th key={h} className="px-5 py-3 font-bold">{h}</th>)}</tr></thead><tbody>{rows.map((row, i) => <tr key={i} className="border-t border-subtle hover:bg-surface-muted">{row.map((cell, j) => <td key={j} className={`px-5 py-4 ${j === row.length - 1 ? "font-bold text-fg" : "text-muted"}`}>{cell}</td>)}</tr>)}</tbody></table></div> }

export function SalesReportPreview() {
  const [tab, setTab] = useState("Resumo")
  const [advanced, setAdvanced] = useState(false)
  const [exportOpen, setExportOpen] = useState(false)
  return <main className="min-h-screen bg-canvas text-fg"><div className="mx-auto max-w-[1480px] space-y-5 p-4 sm:p-6 lg:p-8">
    <header className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><div className="mb-3 flex items-center gap-2"><span className="grid size-9 place-items-center rounded-xl bg-primary text-sm font-black text-white">C</span><span className="text-sm font-bold tracking-[.16em] text-primary">CORE PDV</span><span className="rounded-full bg-info-surface px-2 py-1 text-[10px] font-bold text-primary">PREVIEW</span></div><h1 className="text-3xl font-bold tracking-tight sm:text-4xl">Relatório de vendas</h1><p className="mt-1 text-sm text-muted">Visão operacional do desempenho comercial da sua filial.</p></div><div className="relative flex gap-2"><button className="btn btn-secondary" onClick={() => setExportOpen(!exportOpen)}><Download className="size-4" /> Exportar <ChevronDown className="size-4" /></button>{exportOpen && <div className="absolute right-0 top-12 z-10 w-52 rounded-xl border border-subtle bg-surface p-2 shadow-xl"><button className="flex w-full items-center gap-3 rounded-lg px-3 py-2 text-sm hover:bg-surface-muted"><FileText className="size-4 text-danger" /> PDF completo</button><button className="flex w-full items-center gap-3 rounded-lg px-3 py-2 text-sm hover:bg-surface-muted"><FileSpreadsheet className="size-4 text-success" /> Excel completo</button></div>}</div></header>
    <Card className="p-4"><div className="flex flex-col gap-4 lg:flex-row lg:items-center lg:justify-between"><div className="flex flex-wrap gap-2"><button className="rounded-lg bg-info-surface px-3 py-2 text-xs font-bold text-primary">Hoje</button><button className="rounded-lg border border-subtle px-3 py-2 text-xs font-semibold text-muted">7 dias</button><button className="rounded-lg border border-subtle px-3 py-2 text-xs font-semibold text-muted">30 dias</button><button className="rounded-lg border border-subtle px-3 py-2 text-xs font-semibold text-muted">01 jun — 30 jun 2026</button></div><div className="flex gap-2"><button className="btn btn-secondary" onClick={() => setAdvanced(!advanced)}><Filter className="size-4" /> + Filtros <span className="rounded-full bg-primary px-1.5 text-[10px] text-white">4</span></button><button className="btn btn-primary">Aplicar</button></div></div>{advanced && <div className="mt-4 grid gap-3 border-t border-subtle pt-4 sm:grid-cols-2 lg:grid-cols-4"><label className="text-xs font-semibold">Categoria<select className="input mt-1"><option>Todas as categorias</option></select></label><label className="text-xs font-semibold">Atendente<select className="input mt-1"><option>Todos os atendentes</option></select></label><label className="text-xs font-semibold">Pagamento<select className="input mt-1"><option>Todos os pagamentos</option></select></label><label className="text-xs font-semibold">Status<select className="input mt-1"><option>Concluídas e canceladas</option></select></label></div>}</Card>
    <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Card className="p-5"><div className="flex justify-between"><span className="text-xs font-bold text-muted">Faturamento</span><BarChart3 className="size-5 text-primary" /></div><strong className="mt-4 block text-2xl">R$ 9.386,10</strong><span className="mt-1 block text-xs font-semibold text-success-strong">+12,8% vs. período anterior</span></Card><Card className="p-5"><div className="flex justify-between"><span className="text-xs font-bold text-muted">Vendas concluídas</span><ShoppingCart className="size-5 text-primary" /></div><strong className="mt-4 block text-2xl">98</strong><span className="mt-1 block text-xs font-semibold text-success-strong">+8,4% no período</span></Card><Card className="p-5"><div className="flex justify-between"><span className="text-xs font-bold text-muted">Ticket médio</span><WalletCards className="size-5 text-primary" /></div><strong className="mt-4 block text-2xl">R$ 95,78</strong><span className="mt-1 block text-xs font-semibold text-muted">R$ 4,20 acima da média</span></Card><Card className="p-5"><div className="flex justify-between"><span className="text-xs font-bold text-muted">Itens vendidos</span><Package className="size-5 text-primary" /></div><strong className="mt-4 block text-2xl">257</strong><span className="mt-1 block text-xs font-semibold text-warning-strong">2,6 itens por venda</span></Card></div>
    <div className="flex gap-1 overflow-x-auto border-b border-subtle">{tabs.map(t => <button key={t} onClick={() => setTab(t)} className={`whitespace-nowrap border-b-2 px-4 py-3 text-sm font-bold transition ${tab === t ? "border-primary text-primary" : "border-transparent text-muted hover:text-fg"}`}>{t}</button>)}</div>
    {tab === "Resumo" && <div className="grid gap-5 lg:grid-cols-[1.5fr_1fr]"><Card className="p-5"><div className="flex items-start justify-between"><div><h2 className="text-lg font-bold">Faturamento por hora</h2><p className="mt-1 text-xs text-muted">Distribuição das vendas no período selecionado</p></div><MoreHorizontal className="size-5 text-muted" /></div><MiniChart /><div className="mt-5 flex flex-wrap gap-6 text-xs"><span><i className="mr-2 inline-block size-2 rounded-full bg-primary" />Faturamento <strong>R$ 9.386,10</strong></span><span><i className="mr-2 inline-block size-2 rounded-full bg-success" />Período anterior <strong>R$ 8.321,40</strong></span></div></Card><Card className="p-5"><h2 className="text-lg font-bold">Meios de pagamento</h2><p className="mt-1 text-xs text-muted">Participação no faturamento</p><div className="flex items-center justify-around gap-4 py-7"><Donut /><div className="space-y-3 text-xs">{[["Pix","52%","bg-primary"],["Cartão","34%","bg-info"],["Dinheiro","11%","bg-success"],["Débito","3%","bg-warning"]].map(([l,v,c]) => <div key={l} className="flex items-center gap-2"><i className={`size-2 rounded-full ${c}`} /> <span className="text-muted">{l}</span><strong>{v}</strong></div>)}</div></div></Card><Card className="p-5 lg:col-span-2"><h2 className="text-lg font-bold">Análise do período</h2><p className="mt-1 max-w-3xl text-sm leading-6 text-muted">O faturamento cresceu <strong className="text-fg">12,8%</strong> em relação ao período anterior. O pico de operação acontece entre 12h e 14h, enquanto o Pix representa a maior participação entre os meios de pagamento.</p></Card></div>}
    {tab === "Vendas" && <Card><div className="flex items-center justify-between p-5"><div><h2 className="text-lg font-bold">Vendas realizadas</h2><p className="mt-1 text-xs text-muted">98 vendas no recorte atual</p></div><button className="icon-button"><X className="size-4" /></button></div><Table headers={["Venda", "Data e hora", "Cliente", "Pagamento", "Status", "Total"]} rows={sales} /></Card>}
    {tab === "Itens" && <Card><div className="p-5"><h2 className="text-lg font-bold">Itens vendidos</h2><p className="mt-1 text-xs text-muted">Produtos com maior volume no período</p></div><Table headers={["Produto", "Categoria", "Quantidade", "Faturamento"]} rows={items} /></Card>}
    {tab === "Pagamentos" && <Card><div className="p-5"><h2 className="text-lg font-bold">Pagamentos das vendas</h2><p className="mt-1 text-xs text-muted">Conciliação por meio de pagamento</p></div><Table headers={["Meio de pagamento", "Vendas", "Total recebido", "Participação"]} rows={payments} /></Card>}
    {tab === "Vendas por hora" && <div className="grid gap-5 lg:grid-cols-[1.5fr_1fr]"><Card className="p-5"><h2 className="text-lg font-bold">Ritmo de vendas</h2><p className="mt-1 text-xs text-muted">Quantidade de vendas por hora do dia</p><MiniChart /></Card><Card className="p-5"><h2 className="text-lg font-bold">Melhor janela</h2><strong className="mt-5 block text-4xl text-primary">12h — 14h</strong><p className="mt-2 text-sm leading-6 text-muted">Concentra 31% do faturamento e 28 vendas concluídas.</p></Card></div>}
    <footer className="flex flex-col justify-between gap-2 border-t border-subtle pt-4 text-[11px] text-muted sm:flex-row"><span>CORE PDV · Empresa Demo · Filial Centro</span><span>Dados representativos para visualização do piloto</span></footer>
  </div></main>
}

export default SalesReportPreview
