from decimal import Decimal, InvalidOperation


EXPORT_LABELS = {
    'id': 'ID',
    'sale_number': 'Número',
    'operation_type': 'Operação',
    'status': 'Status',
    'operator': 'Operador',
    'seller': 'Atendente',
    'beneficiary': 'Beneficiário',
    'subtotal': 'Valor bruto',
    'promotion_discount_total': 'Desconto promocional',
    'item_discount_total': 'Desconto manual por item',
    'manual_discount': 'Desconto manual por item',
    'discount': 'Desconto manual na conta',
    'service_fee_amount': 'Taxa de serviço',
    'commission_amount': 'Comissão',
    'total': 'Total cobrado',
    'created_at': 'Criado em',
    'cancelled_at': 'Cancelado em',
    'items': 'Itens',
    'payments': 'Pagamentos',
    'opened_at': 'Aberto em',
    'closed_at': 'Fechado em',
    'register': 'Caixa',
    'opening': 'Abertura',
    'manual_entries': 'Entradas manuais',
    'cash_payments': 'Pagamentos em dinheiro',
    'sale_cash': 'Vendas em dinheiro',
    'consumption_cash': 'Consumações em dinheiro',
    'cash_reversals': 'Reversões em dinheiro',
    'cash_cancellations': 'Cancelamentos com dinheiro',
    'withdrawals': 'Sangrias',
    'expected': 'Esperado em dinheiro',
    'informed': 'Informado no fechamento',
    'difference': 'Diferença',
    'amount': 'Valor',
    'category': 'Categoria',
    'category_label': 'Categoria',
    'cash_register': 'Caixa',
    'reason': 'Motivo',
    'result_effect': 'Impacto no resultado',
    'movement_type': 'Movimento',
    'product': 'Produto',
    'previous_quantity': 'Saldo anterior',
    'quantity': 'Quantidade',
    'final_quantity': 'Saldo final',
    'user': 'Usuário',
    'sale': 'Venda',
    'name': 'Nome',
    'code': 'Código',
    'product_name': 'Nome do produto',
    'internal_code': 'Código interno',
    'unit': 'Unidade',
    'promotion': 'Promoção',
    'promotion_discount_type': 'Tipo do desconto promocional',
    'promotion_discount_value': 'Valor do desconto promocional',
    'promotion_benefit': 'Benefício promocional',
    'promotion_value_raw': 'Valor configurado da promoção',
    'net_subtotal': 'Subtotal líquido',
    'payment_method_name': 'Forma de pagamento',
    'payment_method_code': 'Identificador',
    'unit_price': 'Preço unitário',
    'promotion_name': 'Promoção',
    'origin': 'Origem',
    'gross_quantity': 'Quantidade bruta',
    'returned_quantity': 'Devoluções',
    'net_quantity': 'Quantidade líquida',
    'estimated_cost': 'Custo estimado pelo custo atual',
    'movement_count': 'Movimentos',
    'nature': 'Natureza',
    'operation_reference': 'Referência da operação',
    'count': 'Quantidade',
    'inflow_count': 'Entradas',
    'reversal_count': 'Reversões',
    'ranking_type': 'Tipo de classificação',
    'revenue': 'Faturamento de vendas',
    'gross': 'Valor bruto',
    'account_discount': 'Desconto manual na conta',
    'item_discount': 'Desconto manual por item',
    'promotion_discount': 'Desconto promocional',
    'sales_revenue': 'Faturamento de vendas',
    'effective_revenue': 'Faturamento efetivo',
    'service_fee': 'Taxa de serviço',
    'total_received': 'Total recebido',
    'payment_total': 'Total dos pagamentos',
    'reconciliation_delta': 'Delta de reconciliação',
    'costs_and_expenses': 'Custos e despesas',
    'commission': 'Comissão',
    'cancellation_count': 'Cancelamentos',
    'cancellation_value': 'Valor cancelado',
    'customer_total': 'Total cobrado',
    'average': 'Ticket médio',
    'reference': 'Valor de referência',
    'charged': 'Valor cobrado',
    'subsidy': 'Benefício concedido',
    'payment_totals': 'Totais por forma de pagamento',
    'sales_count': 'Vendas',
    'sales_cancellation_count': 'Vendas canceladas',
    'sales_cancellation_value': 'Valor de vendas canceladas',
    'consumption_count': 'Consumações',
    'consumption_reference': 'Referência de consumações',
    'consumption_charged': 'Consumações cobradas',
    'consumption_benefit': 'Benefício de consumações',
    'consumption_cancellation_count': 'Consumações canceladas',
    'consumption_cancellation_value': 'Valor de consumações canceladas',
    'statement': 'Indicador',
    'value': 'Valor',
    'notice': 'Observação',
    'scope': 'Escopo',
    'period_start': 'Período solicitado - início',
    'period_end': 'Período solicitado - fim',
    'period_sales_count': 'Período solicitado - vendas',
    'period_sales_revenue': 'Período solicitado - faturamento de vendas',
    'period_effective_revenue': 'Período solicitado - faturamento efetivo',
    'period_service_fee': 'Período solicitado - taxa de serviço',
    'period_total_received': 'Período solicitado - total recebido',
    'period_payment_total': 'Período solicitado - total dos pagamentos',
    'period_reconciliation_delta': 'Período solicitado - delta de reconciliação',
    'period_consumption_count': 'Período solicitado - consumações',
    'period_consumption_charged': 'Período solicitado - consumação cobrada',
    'period_reversals': 'Período solicitado - reversões',
    'period_manual_entries': 'Período solicitado - entradas manuais',
    'period_withdrawals': 'Período solicitado - sangrias',
    'period_payment_totals': 'Período solicitado - recebimentos por forma',
    'period_commission': 'Período solicitado - comissão',
    'session_id': 'Sessão - ID',
    'session_opened_at': 'Sessão - abertura',
    'session_closed_at': 'Sessão - fechamento',
    'session_status': 'Sessão - status',
    'session_register': 'Sessão - caixa',
    'session_operator': 'Sessão - operador',
    'complete_session_opening': 'Valores da sessão completa - abertura',
    'complete_session_manual_entries': 'Valores da sessão completa - entradas manuais',
    'complete_session_sale_cash': 'Valores da sessão completa - vendas em dinheiro',
    'complete_session_consumption_cash': 'Valores da sessão completa - consumações em dinheiro',
    'complete_session_cash_reversals': 'Valores da sessão completa - reversões em dinheiro',
    'complete_session_withdrawals': 'Valores da sessão completa - sangrias',
    'complete_session_expected': 'Valores da sessão completa - esperado em dinheiro',
    'complete_session_informed': 'Valores da sessão completa - informado no fechamento',
    'complete_session_difference': 'Valores da sessão completa - diferença',
    'complete_session_sales_count': 'Valores da sessão completa - vendas',
    'complete_session_sales_revenue': 'Valores da sessão completa - faturamento de vendas',
    'complete_session_effective_revenue': 'Valores da sessão completa - faturamento efetivo',
    'event_type': 'Tipo do evento',
    'event_at': 'Data do evento',
    'event_sign': 'Sinal do evento',
    'complete_session_service_fee': 'Valores da sessão completa - taxa de serviço',
    'complete_session_total_received': 'Valores da sessão completa - total recebido',
    'complete_session_payment_total': 'Valores da sessão completa - total dos pagamentos',
    'complete_session_reconciliation_delta': 'Valores da sessão completa - delta de reconciliação',
    'complete_session_consumption_count': 'Valores da sessão completa - consumações',
    'complete_session_consumption_charged': 'Valores da sessão completa - consumação cobrada',
    'complete_session_payment_totals': 'Valores da sessão completa - recebimentos por forma',
    'complete_session_commission': 'Valores da sessão completa - comissão',
    'sales_payment_total': 'Pagamentos de vendas',
    'consumption_payment_total': 'Pagamentos de consumações',
    'payment_total_before_reversals': 'Pagamentos antes das reversões',
    'reversal_payment_total': 'Pagamentos revertidos',
    'row_type': 'Tipo de linha',
    'ordered_total': 'Valor pedido',
    'received_total': 'Valor recebido',
    'unreceived_total': 'Valor não recebido',
    'ordered_quantity': 'Quantidade pedida',
    'received_quantity': 'Quantidade recebida',
    'unreceived_quantity': 'Quantidade não recebida',
    'item_details': 'Detalhamento por item',
}


EXPORT_VALUES = {
    'finalized': 'Finalizada',
    'cancelled': 'Cancelada',
    'sale': 'Venda',
    'consumption': 'Consumação',
    'open': 'Aberta',
    'closed': 'Fechada',
    'manual_entry': 'Entrada manual',
    'withdrawal': 'Sangria',
    'entry': 'Entrada',
    'exit': 'Saída',
    'adjustment': 'Ajuste',
    'operating_expense': 'Despesa operacional',
    'neutral': 'Não afeta o resultado',
    'unclassified': 'Não classificado',
    'cash': 'Dinheiro',
    'pix': 'PIX',
    'credit_card': 'Cartão de crédito',
    'debit_card': 'Cartão de débito',
    'fixed_amount': 'Valor fixo',
    'percentage': 'Percentual',
    'manual_exit': 'Saída manual',
    'reversal': 'Reversão/cancelamento',
    'sale_cancellation': 'Cancelamento de venda',
    'consumption_cancellation': 'Cancelamento de consumação',
    'bonus': 'Bonificada',
    'return': 'Devolução',
    'opening_balance': 'Saldo inicial',
    'correction': 'Correção',
    'transfer': 'Transferência',
    'damage': 'Avaria',
    'loss': 'Perda',
    'internal_use': 'Uso interno',
    'inventory': 'Inventário',
    'regularization': 'Regularização',
    'balance_correction': 'Correção de saldo',
    'normal': 'Normal',
    'other': 'Outros',
    'requested_period': 'Período solicitado',
    'complete_session_values': 'Valores da sessão completa',
    'inflow': 'Entrada',
    'reconciliation': 'Reconciliação',
    'payment_method': 'Forma de pagamento',
    'add': 'Adicionar',
    'remove': 'Remover',
    'observation': 'Observação',
    'text': 'Texto',
    'product_input': 'Produto ou insumo',
    'component_substitution': 'Substituição de componente',
    'counter': 'Balcão',
    'table': 'Mesa',
    'command': 'Comanda',
    'active': 'Ativo',
    'inactive': 'Inativo',
}


def promotion_discount_type_label(value):
    return EXPORT_VALUES.get(value, value or '')


def promotion_discount_value_label(discount_type, value):
    try:
        decimal_value = Decimal(value or 0)
    except (InvalidOperation, TypeError, ValueError):
        return ''
    if discount_type == 'percentage':
        normalized = format(decimal_value.normalize(), 'f').rstrip('0').rstrip('.')
        return f'{normalized.replace(".", ",")}%'
    return f'R$ {decimal_value.quantize(Decimal("0.01")):,.2f}'.replace(',', 'X').replace('.', ',').replace('X', '.')


def export_label(value):
    return EXPORT_LABELS.get(value, value)


def export_value(value):
    if isinstance(value, dict):
        return {export_label(key): export_value(item) for key, item in value.items()}
    if isinstance(value, list):
        return [export_value(item) for item in value]
    if isinstance(value, str):
        return EXPORT_VALUES.get(value, value)
    return value
