EXPORT_LABELS = {
    'id': 'ID',
    'sale_number': 'Número',
    'operation_type': 'Operação',
    'status': 'Status',
    'operator': 'Operador',
    'seller': 'Atendente',
    'beneficiary': 'Beneficiário',
    'subtotal': 'Valor bruto',
    'promotion_discount_total': 'Desconto promocional',
    'item_discount_total': 'Desconto manual por item',
    'manual_discount': 'Desconto manual por item',
    'discount': 'Desconto manual na conta',
    'service_fee_amount': 'Taxa de serviço',
    'commission_amount': 'Comissão',
    'total': 'Total cobrado',
    'created_at': 'Criado em',
    'cancelled_at': 'Cancelado em',
    'items': 'Itens',
    'payments': 'Pagamentos',
    'opened_at': 'Aberto em',
    'closed_at': 'Fechado em',
    'register': 'Caixa',
    'opening': 'Abertura',
    'manual_entries': 'Entradas manuais',
    'cash_payments': 'Pagamentos em dinheiro',
    'withdrawals': 'Sangrias',
    'expected': 'Esperado em dinheiro',
    'informed': 'Informado no fechamento',
    'difference': 'Diferença',
    'amount': 'Valor',
    'category': 'Categoria',
    'category_label': 'Categoria',
    'cash_register': 'Caixa',
    'reason': 'Motivo',
    'result_effect': 'Impacto no resultado',
    'movement_type': 'Movimento',
    'product': 'Produto',
    'previous_quantity': 'Saldo anterior',
    'quantity': 'Quantidade',
    'final_quantity': 'Saldo final',
    'user': 'Usuário',
    'sale': 'Venda',
    'name': 'Nome',
    'code': 'Código',
    'product_name': 'Nome do produto',
    'internal_code': 'Código interno',
    'unit': 'Unidade',
    'promotion': 'Promoção',
    'promotion_discount_type': 'Tipo do desconto promocional',
    'promotion_discount_value': 'Valor do desconto promocional',
    'promotion_benefit': 'Beneficio promocional',
    'net_subtotal': 'Subtotal líquido',
    'payment_method_name': 'Forma de pagamento',
    'payment_method_code': 'Identificador',
    'unit_price': 'Preço unitário',
    'promotion_name': 'Promoção',
    'origin': 'Origem',
    'gross_quantity': 'Quantidade bruta',
    'returned_quantity': 'Devoluções',
    'net_quantity': 'Quantidade líquida',
    'estimated_cost': 'Custo estimado',
    'movement_count': 'Movimentos',
    'nature': 'Natureza',
    'operation_reference': 'Referência da operação',
    'count': 'Quantidade',
    'gross': 'Valor bruto',
    'account_discount': 'Desconto manual na conta',
    'item_discount': 'Desconto manual por item',
    'promotion_discount': 'Desconto promocional',
    'effective_revenue': 'Faturamento efetivo',
    'service_fee': 'Taxa de serviço',
    'commission': 'Comissão',
    'customer_total': 'Total cobrado',
    'average': 'Ticket medio',
    'reference': 'Valor de referência',
    'charged': 'Valor cobrado',
    'subsidy': 'Beneficio concedido',
    'payment_totals': 'Totais por forma de pagamento',
    'sales_count': 'Vendas',
    'consumption_count': 'Consumacoes',
    'consumption_reference': 'Referência de consumações',
    'consumption_charged': 'Consumações cobradas',
    'consumption_benefit': 'Benefício de consumações',
    'statement': 'Indicador',
    'value': 'Valor',
    'notice': 'Observação',
}


EXPORT_VALUES = {
    'finalized': 'Finalizada',
    'cancelled': 'Cancelada',
    'sale': 'Venda',
    'consumption': 'Consumação',
    'open': 'Aberta',
    'closed': 'Fechada',
    'manual_entry': 'Entrada manual',
    'withdrawal': 'Sangria',
    'entry': 'Entrada',
    'exit': 'Saída',
    'adjustment': 'Ajuste',
    'operating_expense': 'Despesa operacional',
    'neutral': 'Não afeta o resultado',
    'unclassified': 'Não classificado',
    'cash': 'Dinheiro',
    'pix': 'PIX',
    'credit_card': 'Cartão de crédito',
    'debit_card': 'Cartão de débito',
    'fixed_amount': 'Valor fixo',
    'percentage': 'Percentual',
    'manual_exit': 'Saída manual',
    'reversal': 'Reversão/cancelamento',
    'sale_cancellation': 'Cancelamento de venda',
    'consumption_cancellation': 'Cancelamento de consumação',
    'bonus': 'Bonificada',
    'return': 'Devolução',
    'opening_balance': 'Saldo inicial',
    'correction': 'Correção',
    'transfer': 'Transferência',
    'damage': 'Avaria',
    'loss': 'Perda',
    'internal_use': 'Uso interno',
    'inventory': 'Inventário',
    'regularization': 'Regularização',
    'balance_correction': 'Correção de saldo',
    'normal': 'Normal',
    'other': 'Outros',
}


def export_label(value):
    return EXPORT_LABELS.get(value, value)


def export_value(value):
    if isinstance(value, dict):
        return {export_label(key): export_value(item) for key, item in value.items()}
    if isinstance(value, list):
        return [export_value(item) for item in value]
    if isinstance(value, str):
        return EXPORT_VALUES.get(value, value)
    return value
