# Generated by Django 6.1 on 2026-08-23

import decimal
import django.db.models.deletion
from django.db import migrations, models

import apps.suppliers.validators


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('companies', '0029_v2_3_supplier_permissions'),
        ('products', '0007_alter_product_inventory_behavior'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('legal_name', models.CharField(max_length=200)),
                ('trade_name', models.CharField(max_length=200)),
                ('tax_id', models.CharField(blank=True, max_length=14, null=True, validators=[apps.suppliers.validators.validate_tax_id])),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('contact_name', models.CharField(blank=True, max_length=150)),
                ('address', models.JSONField(blank=True, default=dict)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('active', 'Ativo'), ('inactive', 'Inativo')], default='active', max_length=10)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='suppliers', to='companies.company')),
            ],
            options={'ordering': ('trade_name', 'legal_name', 'id')},
        ),
        migrations.CreateModel(
            name='ProductSupplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('supplier_code', models.CharField(blank=True, max_length=100)),
                ('is_preferred', models.BooleanField(default=False)),
                ('is_exclusive', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('active', 'Ativo'), ('inactive', 'Inativo')], default='active', max_length=10)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_suppliers', to='companies.company')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_suppliers', to='products.product')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_suppliers', to='suppliers.supplier')),
            ],
            options={'ordering': ('product__name', '-is_exclusive', '-is_preferred', 'supplier__trade_name')},
        ),
        migrations.CreateModel(
            name='ProductSupplierUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('unit_code', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=200)),
                ('conversion_factor', models.DecimalField(decimal_places=6, default=decimal.Decimal('1.000000'), max_digits=18)),
                ('barcode', models.CharField(blank=True, max_length=100)),
                ('is_default', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('active', 'Ativo'), ('inactive', 'Inativo')], default='active', max_length=10)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_supplier_units', to='companies.company')),
                ('product_supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='units', to='suppliers.productsupplier')),
            ],
            options={'ordering': ('product_supplier_id', '-is_default', 'unit_code', 'id')},
        ),
        migrations.AddConstraint(
            model_name='supplier',
            constraint=models.UniqueConstraint(condition=models.Q(('tax_id__isnull', False)), fields=('company', 'tax_id'), name='suppliers_supplier_company_tax_id_unique'),
        ),
        migrations.AddConstraint(
            model_name='productsupplier',
            constraint=models.UniqueConstraint(fields=('product', 'supplier'), name='suppliers_product_supplier_pair_unique'),
        ),
        migrations.AddConstraint(
            model_name='productsupplier',
            constraint=models.UniqueConstraint(condition=models.Q(('is_preferred', True), ('status', 'active')), fields=('product',), name='suppliers_product_one_active_preferred'),
        ),
        migrations.AddConstraint(
            model_name='productsupplier',
            constraint=models.UniqueConstraint(condition=models.Q(('is_exclusive', True), ('status', 'active')), fields=('product',), name='suppliers_product_one_active_exclusive'),
        ),
        migrations.AddConstraint(
            model_name='productsupplier',
            constraint=models.CheckConstraint(condition=models.Q(('status', 'inactive'), ('is_exclusive', False), ('is_preferred', True), _connector='OR'), name='suppliers_active_exclusive_is_preferred'),
        ),
        migrations.AddConstraint(
            model_name='productsupplierunit',
            constraint=models.CheckConstraint(condition=models.Q(('conversion_factor__gt', 0)), name='suppliers_unit_conversion_factor_positive'),
        ),
        migrations.AddConstraint(
            model_name='productsupplierunit',
            constraint=models.UniqueConstraint(condition=models.Q(('is_default', True), ('status', 'active')), fields=('product_supplier',), name='suppliers_product_supplier_one_active_default'),
        ),
    ]
