# Generated by Django 6.1 on 2026-08-23 04:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0028_usercompanyaccess_saas_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Capability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=80, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('value_type', models.CharField(choices=[('BOOLEAN', 'Habilitado/desabilitado'), ('INTEGER', 'Limite numerico')], max_length=10)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('code',),
            },
        ),
        migrations.CreateModel(
            name='GlobalSaaSSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('singleton', models.BooleanField(default=True, editable=False, unique=True)),
                ('auto_approve_signups', models.BooleanField(default=True)),
                ('past_due_days', models.PositiveSmallIntegerField(default=3)),
                ('restricted_after_days', models.PositiveSmallIntegerField(default=10)),
                ('support_session_minutes', models.PositiveSmallIntegerField(default=60)),
                ('platform_name', models.CharField(default='CORE PDV', max_length=100)),
                ('logo_url', models.URLField(blank=True)),
                ('compact_logo_url', models.URLField(blank=True)),
                ('favicon_url', models.URLField(blank=True)),
                ('primary_color', models.CharField(default='#111827', max_length=20)),
                ('support_email', models.EmailField(blank=True, max_length=254)),
                ('support_phone', models.CharField(blank=True, max_length=30)),
                ('support_whatsapp', models.CharField(blank=True, max_length=30)),
                ('institutional_links', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='PlatformPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=80, unique=True)),
                ('label', models.CharField(max_length=120)),
            ],
            options={
                'ordering': ('code',),
            },
        ),
        migrations.CreateModel(
            name='PlanVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='BRL', max_length=3)),
                ('billing_period_months', models.PositiveSmallIntegerField(default=1)),
                ('trial_days', models.PositiveSmallIntegerField(default=0)),
                ('is_public', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='versions', to='saas.plan')),
            ],
            options={
                'ordering': ('plan__name', '-version'),
            },
        ),
        migrations.CreateModel(
            name='PlanEntitlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('enabled', models.BooleanField(default=True)),
                ('unlimited', models.BooleanField(default=False)),
                ('limit_value', models.PositiveIntegerField(blank=True, null=True)),
                ('capability', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entitlements', to='saas.capability')),
                ('plan_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entitlements', to='saas.planversion')),
            ],
            options={
                'ordering': ('capability__code',),
            },
        ),
        migrations.CreateModel(
            name='PlatformRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=100)),
                ('is_system', models.BooleanField(default=False)),
                ('permissions', models.ManyToManyField(blank=True, related_name='roles', to='saas.platformpermission')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='PlatformUserAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_accesses', to='saas.platformrole')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='platform_access', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('billing_mode', models.CharField(choices=[('PAID', 'Pago'), ('FREE', 'Gratuito'), ('INTERNAL', 'Interno')], max_length=10)),
                ('status', models.CharField(choices=[('TRIALING', 'Em trial'), ('ACTIVE', 'Ativa'), ('PAST_DUE', 'Inadimplente'), ('RESTRICTED', 'Restrita'), ('SUSPENDED_FINANCIAL', 'Suspensa financeiramente'), ('TRIAL_EXPIRED', 'Trial expirado'), ('CANCELLED', 'Cancelada'), ('SUPERSEDED', 'Substituida por mudanca de plano')], max_length=25)),
                ('is_current', models.BooleanField(default=True)),
                ('current_period_start', models.DateTimeField()),
                ('current_period_end', models.DateTimeField()),
                ('trial_started_at', models.DateTimeField(blank=True, null=True)),
                ('trial_ends_at', models.DateTimeField(blank=True, null=True)),
                ('cancel_at_period_end', models.BooleanField(default=False)),
                ('cancellation_reason', models.TextField(blank=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='companies.company')),
                ('plan_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='saas.planversion')),
            ],
            options={
                'ordering': ('-created_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='ProvisioningOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source', models.CharField(choices=[('PUBLIC_SIGNUP', 'Autoatendimento'), ('PLATFORM_MANUAL', 'Plataforma')], max_length=20)),
                ('idempotency_key', models.CharField(max_length=100)),
                ('request_fingerprint', models.CharField(max_length=64)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='provisioning_operation', to='companies.company')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('subscription', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='provisioning_operation', to='saas.subscription')),
            ],
        ),
        migrations.CreateModel(
            name='CycleUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('period_start', models.DateTimeField()),
                ('period_end', models.DateTimeField()),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('capability', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usage_history', to='saas.capability')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usage_history', to='saas.subscription')),
            ],
            options={
                'ordering': ('-period_start', 'capability__code'),
            },
        ),
        migrations.CreateModel(
            name='BillingRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('paid_at', models.DateTimeField()),
                ('payment_method', models.CharField(max_length=50)),
                ('note', models.TextField(blank=True)),
                ('competency_start', models.DateTimeField()),
                ('competency_end', models.DateTimeField()),
                ('idempotency_key', models.CharField(max_length=100)),
                ('request_fingerprint', models.CharField(max_length=64)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='saas_billing_records', to=settings.AUTH_USER_MODEL)),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='billing_records', to='saas.subscription')),
            ],
            options={
                'ordering': ('-paid_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='SubscriptionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('request_type', models.CharField(choices=[('PLAN_CHANGE', 'Mudanca de plano'), ('CANCELLATION', 'Cancelamento')], max_length=20)),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('PENDING', 'Pendente'), ('APPROVED', 'Aprovada'), ('REJECTED', 'Rejeitada')], default='PENDING', max_length=10)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscription_requests', to=settings.AUTH_USER_MODEL)),
                ('requested_plan_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subscription_requests', to='saas.planversion')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='resolved_subscription_requests', to=settings.AUTH_USER_MODEL)),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='change_requests', to='saas.subscription')),
            ],
            options={
                'ordering': ('-created_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='SupportSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mode', models.CharField(choices=[('READ_ONLY', 'Somente leitura'), ('READ_WRITE', 'Leitura e escrita')], max_length=10)),
                ('reason', models.TextField()),
                ('expires_at', models.DateTimeField()),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='support_sessions', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='support_sessions', to='companies.company')),
                ('ended_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ended_support_sessions', to=settings.AUTH_USER_MODEL)),
                ('impersonated_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='impersonated_support_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='TenantSaaSState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approval_status', models.CharField(choices=[('PENDING', 'Pendente'), ('APPROVED', 'Aprovado'), ('REJECTED', 'Rejeitado')], default='APPROVED', max_length=10)),
                ('approval_reason', models.TextField(blank=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('admin_suspended_at', models.DateTimeField(blank=True, null=True)),
                ('admin_suspension_reason', models.TextField(blank=True)),
                ('admin_suspended_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='admin_suspended_saas_tenants', to=settings.AUTH_USER_MODEL)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_saas_tenants', to=settings.AUTH_USER_MODEL)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='saas_state', to='companies.company')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddConstraint(
            model_name='planversion',
            constraint=models.UniqueConstraint(fields=('plan', 'version'), name='saas_plan_version_unique'),
        ),
        migrations.AddConstraint(
            model_name='planversion',
            constraint=models.CheckConstraint(condition=models.Q(('price__gte', 0)), name='saas_plan_version_price_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='planversion',
            constraint=models.CheckConstraint(condition=models.Q(('billing_period_months__gte', 1)), name='saas_plan_version_period_positive'),
        ),
        migrations.AddConstraint(
            model_name='planentitlement',
            constraint=models.UniqueConstraint(fields=('plan_version', 'capability'), name='saas_plan_entitlement_unique'),
        ),
        migrations.AddConstraint(
            model_name='planentitlement',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('enabled', False), ('limit_value__isnull', True), ('unlimited', False)), models.Q(('enabled', True), ('limit_value__isnull', True), ('unlimited', True)), models.Q(('enabled', True), ('limit_value__isnull', False), ('unlimited', False)), _connector='OR'), name='saas_plan_entitlement_value_coherent'),
        ),
        migrations.AddConstraint(
            model_name='subscription',
            constraint=models.UniqueConstraint(condition=models.Q(('is_current', True)), fields=('company',), name='saas_subscription_one_current_per_company'),
        ),
        migrations.AddConstraint(
            model_name='subscription',
            constraint=models.CheckConstraint(condition=models.Q(('current_period_start__lt', models.F('current_period_end'))), name='saas_subscription_period_valid'),
        ),
        migrations.AddConstraint(
            model_name='subscription',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'TRIALING'), ('trial_ends_at__isnull', False), ('trial_started_at__isnull', False)), models.Q(('status', 'TRIALING'), _negated=True), _connector='OR'), name='saas_subscription_trial_dates_present'),
        ),
        migrations.AddConstraint(
            model_name='provisioningoperation',
            constraint=models.UniqueConstraint(fields=('source', 'idempotency_key'), name='saas_provisioning_idempotency_unique'),
        ),
        migrations.AddConstraint(
            model_name='cycleusage',
            constraint=models.UniqueConstraint(fields=('subscription', 'capability', 'period_start'), name='saas_cycle_usage_unique'),
        ),
        migrations.AddConstraint(
            model_name='cycleusage',
            constraint=models.CheckConstraint(condition=models.Q(('period_start__lt', models.F('period_end'))), name='saas_cycle_usage_period_valid'),
        ),
        migrations.AddConstraint(
            model_name='billingrecord',
            constraint=models.UniqueConstraint(fields=('subscription', 'idempotency_key'), name='saas_billing_record_idempotency_unique'),
        ),
        migrations.AddConstraint(
            model_name='billingrecord',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='saas_billing_record_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='billingrecord',
            constraint=models.CheckConstraint(condition=models.Q(('competency_start__lt', models.F('competency_end'))), name='saas_billing_record_competency_valid'),
        ),
    ]
