# Generated by Django 6.1 on 2026-08-23 05:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='billingrecord',
            name='proof_reference',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='globalsaassettings',
            name='enforcement_enabled',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name='globalsaassettings',
            name='enforcement_enabled_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='globalsaassettings',
            name='enforcement_enabled_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='enabled_saas_enforcement', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='globalsaassettings',
            name='public_signup_billing_mode',
            field=models.CharField(choices=[('PAID', 'Pago'), ('FREE', 'Gratuito')], default='PAID', max_length=10),
        ),
        migrations.AddField(
            model_name='tenantsaasstate',
            name='archive_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='tenantsaasstate',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tenantsaasstate',
            name='archived_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='archived_saas_tenants', to=settings.AUTH_USER_MODEL),
        ),
    ]
