# Generated by Django 6.1 on 2026-08-24 16:41

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0032_v2_6_product_permissions'),
        ('products', '0009_v2_7_modifiers'),
        ('sales', '0015_v2_7_modifiers'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Command',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('command_number', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('open', 'Aberta'), ('closed', 'Fechada')], default='open', max_length=10)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commands', to='companies.branch')),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='closed_commands', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commands', to='companies.company')),
                ('opened_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='opened_commands', to=settings.AUTH_USER_MODEL)),
                ('sale', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='command', to='sales.sale')),
            ],
            options={
                'ordering': ('-created_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('draft', 'Rascunho'), ('confirmed', 'Confirmado'), ('cancelled', 'Cancelado')], default='draft', max_length=10)),
                ('command', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='commands.command')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('seats', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('active', 'Ativo'), ('inactive', 'Inativo')], default='active', max_length=10)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tables', to='companies.branch')),
            ],
            options={
                'ordering': ('name', 'id'),
            },
        ),
        migrations.AddField(
            model_name='command',
            name='table',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='commands', to='commands.table'),
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=14)),
                ('product_name', models.CharField(max_length=200)),
                ('internal_code', models.CharField(blank=True, max_length=100)),
                ('unit', models.CharField(max_length=5)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=14)),
                ('base_unit_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('modifier_unit_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('modifier_snapshot', models.JSONField(blank=True, default=list)),
                ('unit_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('component_cost_snapshot', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('confirmed', 'Confirmado'), ('cancelled', 'Cancelado')], default='pending', max_length=10)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancellation_reason', models.TextField(blank=True)),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cancelled_order_items', to=settings.AUTH_USER_MODEL)),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='confirmed_order_items', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='commands.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='products.product')),
            ],
            options={
                'ordering': ('id',),
                'constraints': [models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='commands_order_item_quantity_positive'), models.CheckConstraint(condition=models.Q(('unit_price__gte', 0)), name='commands_order_item_price_nonnegative'), models.CheckConstraint(condition=models.Q(('status', 'confirmed'), ('confirmed_at__isnull', True), _connector='OR'), name='commands_order_item_confirmed_requires_timestamp'), models.CheckConstraint(condition=models.Q(('status', 'cancelled'), ('cancelled_at__isnull', True), _connector='OR'), name='commands_order_item_cancelled_requires_timestamp')],
            },
        ),
        migrations.AddConstraint(
            model_name='table',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('branch', 'name'), name='commands_table_branch_name_active_unique'),
        ),
        migrations.AddConstraint(
            model_name='command',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'open')), fields=('branch', 'command_number'), name='commands_open_number_unique'),
        ),
        migrations.AddConstraint(
            model_name='command',
            constraint=models.CheckConstraint(condition=models.Q(('status', 'open'), ('closed_at__isnull', False), _connector='OR'), name='commands_closed_requires_timestamp'),
        ),
    ]
