# Generated by Django 6.1 on 2026-08-25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commands', '0001_v2_8_commands'),
    ]

    operations = [
        migrations.AddField(
            model_name='command',
            name='identifier',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.RemoveConstraint(
            model_name='orderitem',
            name='commands_order_item_confirmed_requires_timestamp',
        ),
        migrations.AddConstraint(
            model_name='orderitem',
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ('status__in', ('confirmed', 'cancelled')),
                    ('confirmed_at__isnull', True),
                    _connector='OR',
                ),
                name='commands_order_item_confirmed_requires_timestamp',
            ),
        ),
    ]
