# Generated by Django 6.1 on 2026-08-26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commands', '0002_command_identifier_and_cancelled_confirmation'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommandOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('operation_type', models.CharField(choices=[('transfer', 'Transfer'), ('transfer_items', 'Transfer Items'), ('merge', 'Merge'), ('split', 'Split')], max_length=20)),
                ('idempotency_key', models.UUIDField(editable=False)),
                ('payload_fingerprint', models.CharField(editable=False, max_length=64)),
                ('result', models.JSONField(default=dict)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='command_operations', to='companies.branch')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='command_operations', to='companies.company')),
            ],
        ),
        migrations.AddConstraint(
            model_name='commandoperation',
            constraint=models.UniqueConstraint(fields=('branch', 'operation_type', 'idempotency_key'), name='commands_operation_branch_type_idempotency_unique'),
        ),
    ]
