# Generated by Django 6.1 on 2026-08-26
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from django.db.models import F, Q


class Migration(migrations.Migration):
    dependencies = [('commands', '0003_command_operation'), ('cash', '0004_cash_movement_operation_reference'), ('sales', '0015_v2_7_modifiers')]
    operations = [
        migrations.CreateModel(
            name='CommandPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)), ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('received_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('change_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('status', models.CharField(choices=[('applied', 'Aplicado'), ('reversed', 'Estornado')], default='applied', max_length=10)),
                ('idempotency_key', models.UUIDField()), ('reversal_reason', models.TextField(blank=True, default='')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='command_payments', to='companies.branch')),
                ('cash_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='command_payments', to='cash.cashsession')),
                ('command', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='commands.command')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='command_payments', to='companies.company')),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='command_payments', to=settings.AUTH_USER_MODEL)),
                ('payment_method', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='command_payments', to='sales.paymentmethod')),
                ('reversal_of', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reversal', to='commands.commandpayment')),
            ],
            options={'ordering': ('id',)},
        ),
        migrations.AddConstraint(model_name='commandpayment', constraint=models.UniqueConstraint(fields=('command', 'idempotency_key'), name='commands_payment_idempotency_unique')),
        migrations.AddConstraint(model_name='commandpayment', constraint=models.CheckConstraint(condition=Q(amount__gt=0), name='commands_payment_amount_positive')),
        migrations.AddConstraint(model_name='commandpayment', constraint=models.CheckConstraint(condition=Q(received_amount__isnull=True) | Q(received_amount__gte=F('amount')), name='commands_payment_received_gte_amount')),
        migrations.AddConstraint(model_name='commandpayment', constraint=models.CheckConstraint(condition=Q(change_amount__isnull=True) | Q(change_amount__gte=0), name='commands_payment_change_nonnegative')),
        migrations.AddConstraint(model_name='commandpayment', constraint=models.CheckConstraint(condition=Q(status='applied', reversal_of__isnull=True, reversal_reason='') | Q(status='reversed', reversal_of__isnull=False), name='commands_payment_status_coherent')),
    ]
