# Generated by Django 6.1 on 2026-08-15 17:38

import apps.companies.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('trade_name', models.CharField(max_length=150)),
                ('legal_name', models.CharField(max_length=200)),
                ('cnpj', models.CharField(blank=True, db_index=True, max_length=14, null=True, validators=[apps.companies.validators.validate_cnpj])),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('status', models.CharField(choices=[('active', 'Ativo'), ('inactive', 'Inativo')], default='active', max_length=10)),
            ],
            options={
                'verbose_name_plural': 'companies',
                'ordering': ('trade_name',),
            },
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('cnpj', models.CharField(blank=True, db_index=True, max_length=14, null=True, validators=[apps.companies.validators.validate_cnpj])),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('active', 'Ativo'), ('inactive', 'Inativo')], default='active', max_length=10)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='branches', to='companies.company')),
            ],
            options={
                'ordering': ('company__trade_name', 'name'),
                'constraints': [models.UniqueConstraint(fields=('company', 'name'), name='companies_branch_company_name_unique')],
            },
        ),
    ]
