# Generated by Django 6.1 on 2026-08-15 17:54

from django.db import migrations, models


def mark_existing_matrices(apps, schema_editor):
    branch = apps.get_model('companies', 'Branch')
    branch.objects.update(is_matrix=False)
    company_ids = branch.objects.filter(name__iexact='Matriz').values_list(
        'company_id', flat=True
    ).distinct()
    for company_id in company_ids:
        matrix_id = branch.objects.filter(
            company_id=company_id,
            name__iexact='Matriz',
        ).order_by('pk').values_list('pk', flat=True).first()
        branch.objects.filter(pk=matrix_id).update(is_matrix=True)


def unmark_existing_matrices(apps, schema_editor):
    branch = apps.get_model('companies', 'Branch')
    branch.objects.update(is_matrix=False)


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('companies', '0002_userbranchaccess_usercompanyaccess'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='is_matrix',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(mark_existing_matrices, unmark_existing_matrices),
        migrations.AddConstraint(
            model_name='branch',
            constraint=models.UniqueConstraint(condition=models.Q(('cnpj__isnull', False)), fields=('cnpj',), name='companies_branch_cnpj_unique'),
        ),
        migrations.AddConstraint(
            model_name='branch',
            constraint=models.UniqueConstraint(condition=models.Q(('is_matrix', True)), fields=('company',), name='companies_branch_one_matrix_per_company'),
        ),
        migrations.AddConstraint(
            model_name='company',
            constraint=models.UniqueConstraint(condition=models.Q(('cnpj__isnull', False)), fields=('cnpj',), name='companies_company_cnpj_unique'),
        ),
    ]
