# Generated by Django 6.1 on 2026-08-15 19:01

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_branch_is_matrix_branch_companies_branch_cnpj_unique_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='company',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('trade_name'), name='companies_company_trade_name_ci_unique'),
        ),
        migrations.AddConstraint(
            model_name='company',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('legal_name'), name='companies_company_legal_name_ci_unique'),
        ),
    ]
