# Generated by Django 6.1 on 2026-08-16 22:32

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0015_promotions_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='BranchSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('allow_negative_stock', models.BooleanField(default=False)),
                ('service_fee_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('commission_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('fixed_daily_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('branch', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='companies.branch')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('service_fee_rate__gte', 0), ('service_fee_rate__lte', 100)), name='companies_branchsettings_service_fee_range'), models.CheckConstraint(condition=models.Q(('commission_rate__gte', 0), ('commission_rate__lte', 100)), name='companies_branchsettings_commission_range'), models.CheckConstraint(condition=models.Q(('fixed_daily_cost__gte', 0)), name='companies_branchsettings_fixed_cost_nonnegative')],
            },
        ),
    ]
