# Generated by Django 6.1 on 2026-08-16 22:35

from django.db import migrations


def create_missing_settings(apps, schema_editor):
    Branch = apps.get_model('companies', 'Branch')
    BranchSettings = apps.get_model('companies', 'BranchSettings')
    existing = set(BranchSettings.objects.values_list('branch_id', flat=True))
    BranchSettings.objects.bulk_create(
        BranchSettings(branch_id=branch_id)
        for branch_id in Branch.objects.exclude(pk__in=existing).values_list('pk', flat=True)
    )


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0016_sprint_11_5'),
    ]

    operations = [
        migrations.RunPython(create_missing_settings, migrations.RunPython.noop),
    ]
