# Generated by Django 6.1 on 2026-08-17 02:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0018_operational_result_permission'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='accessprofile',
            name='commission_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='accessprofile',
            name='receives_commission',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='UserCommissionOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('receives_commission', models.BooleanField(default=True)),
                ('commission_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commission_overrides', to='companies.branch')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='updated_commission_overrides', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commission_overrides', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('branch__company__trade_name', 'branch__name', 'user__email'),
                'constraints': [models.UniqueConstraint(fields=('branch', 'user'), name='companies_user_commission_override_unique')],
            },
        ),
        migrations.CreateModel(
            name='UserPermissionBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reason', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='permission_blocks', to='companies.branch')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permission_blocks', to='companies.company')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_permission_blocks', to=settings.AUTH_USER_MODEL)),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_blocks', to='companies.functionalpermission')),
                ('revoked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='revoked_permission_blocks', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permission_blocks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('company__trade_name', 'branch__name', 'user__email', 'permission__code'),
                'constraints': [models.UniqueConstraint(condition=models.Q(('branch__isnull', False), ('is_active', True)), fields=('company', 'branch', 'user', 'permission'), name='companies_active_branch_user_permission_block_unique'), models.UniqueConstraint(condition=models.Q(('branch__isnull', True), ('is_active', True)), fields=('company', 'user', 'permission'), name='companies_active_company_user_permission_block_unique')],
            },
        ),
    ]
