# Generated by Django 6.1 on 2026-08-18 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0019_accessprofile_commission_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='address_pending',
            field=models.BooleanField(default=False),
        ),
    ]
