# Generated by Django 6.1 on 2026-08-23

from django.db import migrations, models
from django.db.models import Q


def promote_unambiguous_company_owners(apps, schema_editor):
    UserCompanyAccess = apps.get_model('companies', 'UserCompanyAccess')
    owner_company_ids = UserCompanyAccess.objects.filter(is_owner=True).values_list(
        'company_id', flat=True
    )
    candidates_by_company = {}
    candidates = UserCompanyAccess.objects.filter(
        is_active=True,
        access_profile__is_system=True,
        access_profile__name='Administrador',
    ).exclude(company_id__in=owner_company_ids).values(
        'pk',
        'company_id',
        'access_profile__company_id',
        'user__is_active',
        'user__can_login',
    )
    for candidate in candidates.iterator():
        candidates_by_company.setdefault(candidate['company_id'], []).append(candidate)

    owner_ids = []
    for company_id, company_candidates in candidates_by_company.items():
        if len(company_candidates) != 1:
            continue
        candidate = company_candidates[0]
        if (
            candidate['user__is_active']
            and candidate['user__can_login']
            and candidate['access_profile__company_id'] == company_id
        ):
            owner_ids.append(candidate['pk'])

    using = schema_editor.connection.alias if schema_editor else 'default'
    models.QuerySet(model=UserCompanyAccess, using=using).filter(
        pk__in=owner_ids
    ).update(is_owner=True)


class Migration(migrations.Migration):
    dependencies = [
        ('accounts', '0005_login_consistency'),
        ('companies', '0026_localize_item_discount_permission'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='company',
            name='companies_company_trade_name_ci_unique',
        ),
        migrations.RemoveConstraint(
            model_name='company',
            name='companies_company_legal_name_ci_unique',
        ),
        migrations.AddField(
            model_name='usercompanyaccess',
            name='is_owner',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(
            promote_unambiguous_company_owners,
            migrations.RunPython.noop,
        ),
        migrations.AddConstraint(
            model_name='usercompanyaccess',
            constraint=models.UniqueConstraint(
                condition=Q(is_owner=True),
                fields=('company',),
                name='companies_user_company_one_owner',
            ),
        ),
        migrations.AddConstraint(
            model_name='usercompanyaccess',
            constraint=models.CheckConstraint(
                condition=Q(is_owner=False) | Q(is_active=True),
                name='companies_user_company_owner_active',
            ),
        ),
    ]
