# Generated by Django 6.1 on 2026-08-23 04:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0027_v2_1_company_ownership'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='usercompanyaccess',
            name='saas_status',
            field=models.CharField(choices=[('ACTIVE', 'Ativo no plano'), ('SUSPENDED_BY_PLAN_LIMIT', 'Suspenso por limite do plano')], db_default='ACTIVE', default='ACTIVE', max_length=30),
        ),
        migrations.AddConstraint(
            model_name='usercompanyaccess',
            constraint=models.CheckConstraint(condition=models.Q(('is_owner', False), ('saas_status', 'ACTIVE'), _connector='OR'), name='companies_user_company_owner_saas_active'),
        ),
    ]
