# Generated by Django 6.1 on 2026-08-24 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0032_v2_6_product_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessprofile',
            name='archived_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='branchsettings',
            name='charges_service_fee',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='branchsettings',
            name='uses_cash_register',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='branchsettings',
            name='uses_commands',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='branchsettings',
            name='uses_consumption',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='branchsettings',
            name='uses_counter',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='branchsettings',
            name='uses_tables',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usercommissionoverride',
            name='archived_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
