"use client";

import Link from "next/link";
import { useEffect, useState } from "react";
import { ArrowLeft, Plus, Trash2 } from "lucide-react";
import { PageHeader } from "@/components/page-header";
import { Alert, Button, Input, MoneyInput, Select } from "@/components/ui";
import { ApiError, http } from "@/lib/http";
import { useAuth } from "@/providers/auth-provider";
import type { Category, Product } from "@/types";

type Row = { key: number; category: string; name: string; internal_code: string; barcode: string; unit: "un" | "kg" | "l"; cost: string; sale_price: string; inventory_behavior: "direct" | "none"; is_sellable: boolean; is_favorite: boolean };
let nextKey = 1;
const blank = (): Row => ({ key: nextKey++, category: "", name: "", internal_code: "", barcode: "", unit: "un", cost: "0.00", sale_price: "0.00", inventory_behavior: "direct", is_sellable: true, is_favorite: false });

export default function ProductBulkPage() {
  const { user, currentCompany } = useAuth(); const [categories, setCategories] = useState<Category[]>([]); const [rows, setRows] = useState<Row[]>([blank(), blank()]); const [saving, setSaving] = useState(false); const [error, setError] = useState(""); const [success, setSuccess] = useState("");
  useEffect(() => { if (currentCompany) void http.getAll<Category>(`categories/?company=${currentCompany.id}&status=active`).then(setCategories).catch(() => setError("Não foi possível carregar as categorias.")); }, [currentCompany?.id]);
  function update(key: number, field: keyof Row, value: string | boolean) { setRows((items) => items.map((row) => row.key === key ? { ...row, [field]: value } : row)); }
  async function submit() { if (!currentCompany || !user?.is_superuser) return; setSaving(true); setError(""); setSuccess(""); try { const payload = rows.map(({ key: _key, category, ...row }) => ({ ...row, company: currentCompany.id, category: Number(category), cost: row.cost.replace(",", "."), sale_price: row.sale_price.replace(",", ".") })); const result = await http.post<{ count: number; results: Product[] }>("products/bulk-create/", { products: payload }); setSuccess(`${result.count} produtos cadastrados em uma única transação.`); setRows([blank(), blank()]); } catch (caught) { setError(caught instanceof ApiError ? `${caught.message} ${Object.entries(caught.fields).map(([field, values]) => `${field}: ${values.join(" ")}`).join(" ")}` : "Não foi possível concluir o cadastro em lote. Nenhuma linha foi presumida como salva."); } finally { setSaving(false); } }
  if (!user?.is_superuser) return <div className="p-6"><Alert message="Cadastro em lote é exclusivo do superusuário da plataforma." /></div>;
  return <><PageHeader title="Cadastro em lote de produtos" description="Inclusão tabular atômica, com as mesmas validações do cadastro individual." action={<Link href="/produtos" className="btn btn-secondary"><ArrowLeft className="size-4" />Voltar</Link>} /><div className="space-y-4 p-4 sm:p-6 lg:p-8">{error && <Alert message={error} />}{success && <Alert type="success" message={success} />}<section className="card overflow-hidden"><div className="card-header"><h2 className="text-sm font-bold">Linhas do cadastro</h2><Button variant="secondary" onClick={() => setRows((items) => [...items, blank()])}><Plus className="size-4" />Adicionar linha</Button></div><div className="table-wrap"><table className="data-table"><thead><tr><th>Categoria</th><th>Nome</th><th>Código</th><th>Unidade</th><th>Custo</th><th>Preço</th><th>Estoque</th><th></th></tr></thead><tbody>{rows.map((row, index) => <tr key={row.key}><td><Select aria-label={`Categoria linha ${index + 1}`} value={row.category} onChange={(event) => update(row.key, "category", event.target.value)}><option value="">Selecione</option>{categories.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</Select></td><td><Input required value={row.name} onChange={(event) => update(row.key, "name", event.target.value)} /></td><td><Input value={row.internal_code} placeholder="Automático" onChange={(event) => update(row.key, "internal_code", event.target.value)} /></td><td><Select value={row.unit} onChange={(event) => update(row.key, "unit", event.target.value)}><option value="un">UN</option><option value="kg">KG</option><option value="g">G</option><option value="l">L</option><option value="ml">ML</option></Select></td><td><MoneyInput value={row.cost} onValueChange={(value) => update(row.key, "cost", value)} /></td><td><MoneyInput value={row.sale_price} onValueChange={(value) => update(row.key, "sale_price", value)} /></td><td><Select value={row.inventory_behavior} onChange={(event) => update(row.key, "inventory_behavior", event.target.value)}><option value="direct">Próprio</option><option value="none">Sem estoque</option></Select></td><td><button className="icon-button" disabled={rows.length === 1} onClick={() => setRows((items) => items.filter((item) => item.key !== row.key))}><Trash2 className="size-4" /></button></td></tr>)}</tbody></table></div><div className="flex justify-end border-t border-slate-100 p-4"><Button loading={saving} disabled={rows.some((row) => !row.category || !row.name.trim())} onClick={() => void submit()}>Cadastrar {rows.length} produtos</Button></div></section></div></>;
}
