from django.urls import path

from .views import (
    CashReportView,
    CancellationsReportView,
    CommandsReportOptionsView,
    CommandsReportView,
    CommercialComplementsOptionsView,
    ConsumptionsReportView,
    DashboardView,
    InventoryMovementsReportView,
    InventoryCountsReportView,
    OperationalResultReportView,
    CustomersReportView,
    PayablesReportView,
    PhaseThreeReportOptionsView,
    PurchaseReportView,
    PromotionsReportView,
    ReportsOptionsView,
    SalesReportView,
    ModifiersReportView,
    StockConsumptionReportView,
    StockPositionReportView,
    StockTransfersReportView,
    SupplierReportView,
    WithdrawalsReportView,
)


urlpatterns = [
    path('dashboard/', DashboardView.as_view(), name='dashboard'),
    path('reports/sales/', SalesReportView.as_view(), name='report-sales'),
    path('reports/cancellations/', CancellationsReportView.as_view(), name='report-cancellations'),
    path(
        'reports/operational-result/',
        OperationalResultReportView.as_view(),
        name='report-operational-result',
    ),
    path('reports/options/', ReportsOptionsView.as_view(), name='report-options'),
    path(
        'reports/purchase-options/', PhaseThreeReportOptionsView.as_view(),
        name='report-purchase-options',
    ),
    path('reports/command-options/', CommandsReportOptionsView.as_view(), name='report-command-options'),
    path('reports/commands/', CommandsReportView.as_view(), name='report-commands'),
    path('reports/commercial-options/', CommercialComplementsOptionsView.as_view(), name='report-commercial-options'),
    path('reports/promotions/', PromotionsReportView.as_view(), name='report-promotions'),
    path('reports/modifiers/', ModifiersReportView.as_view(), name='report-modifiers'),
    path('reports/customers/', CustomersReportView.as_view(), name='report-customers'),
    path('reports/purchases/', PurchaseReportView.as_view(), name='report-purchases'),
    path('reports/suppliers/', SupplierReportView.as_view(), name='report-suppliers'),
    path('reports/payables/', PayablesReportView.as_view(), name='report-payables'),
    path('reports/consumptions/', ConsumptionsReportView.as_view(), name='report-consumptions'),
    path('reports/cash/', CashReportView.as_view(), name='report-cash'),
    path('reports/withdrawals/', WithdrawalsReportView.as_view(), name='report-withdrawals'),
    path(
        'reports/inventory-movements/',
        InventoryMovementsReportView.as_view(),
        name='report-inventory-movements',
    ),
    path(
        'reports/stock-consumption/',
        StockConsumptionReportView.as_view(),
        name='report-stock-consumption',
    ),
    path(
        'reports/stock-position/',
        StockPositionReportView.as_view(),
        name='report-stock-position',
    ),
    path(
        'reports/inventory-counts/',
        InventoryCountsReportView.as_view(),
        name='report-inventory-counts',
    ),
    path(
        'reports/stock-transfers/',
        StockTransfersReportView.as_view(),
        name='report-stock-transfers',
    ),
]
