import uuid

from django.conf import settings
from django.db import migrations, models
import django.core.validators


class Migration(migrations.Migration):
    initial = True
    dependencies = [('accounts', '0008_pos_access_and_pin'), ('cash', '0001_initial'), ('companies', '0046_branch_licensing_code')]

    operations = [
        migrations.CreateModel(name='POSRequestRateLimit', fields=[('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')), ('created_at', models.DateTimeField(auto_now_add=True)), ('updated_at', models.DateTimeField(auto_now=True)), ('key', models.CharField(max_length=180, unique=True)), ('failures', models.PositiveSmallIntegerField(default=0)), ('locked_until', models.DateTimeField(blank=True, null=True))]),
        migrations.CreateModel(name='POSDevice', fields=[('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)), ('created_at', models.DateTimeField(auto_now_add=True)), ('updated_at', models.DateTimeField(auto_now=True)), ('name', models.CharField(max_length=150)), ('device_type', models.CharField(choices=[('POS', 'POS'), ('STONE_POS', 'Stone POS'), ('TABLET_POS', 'Tablet POS'), ('MOBILE_POS', 'Mobile POS')], default='POS', max_length=20)), ('status', models.CharField(choices=[('PENDING', 'Pendente'), ('ACTIVE', 'Ativo'), ('BLOCKED', 'Bloqueado'), ('REVOKED', 'Revogado'), ('REPLACED', 'Substituido')], db_index=True, default='PENDING', max_length=10)), ('credential_hash', models.CharField(blank=True, default='', max_length=256)), ('app_version', models.CharField(blank=True, max_length=50)), ('os_version', models.CharField(blank=True, max_length=100)), ('device_model', models.CharField(blank=True, max_length=100)), ('hardware_identifier_hash', models.CharField(blank=True, max_length=256)), ('capabilities', models.JSONField(blank=True, default=dict)), ('paired_at', models.DateTimeField(blank=True, null=True)), ('last_seen_at', models.DateTimeField(blank=True, null=True)), ('blocked_at', models.DateTimeField(blank=True, null=True)), ('revoked_at', models.DateTimeField(blank=True, null=True)), ('replaced_at', models.DateTimeField(blank=True, null=True)), ('branch', models.ForeignKey(on_delete=models.deletion.PROTECT, related_name='pos_devices', to='companies.branch')), ('replaced_by', models.ForeignKey(blank=True, null=True, on_delete=models.deletion.PROTECT, related_name='replaces', to='pos.posdevice'))], options={'ordering': ('branch__name', 'name')}),
        migrations.CreateModel(name='PairingFlow', fields=[('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)), ('created_at', models.DateTimeField(auto_now_add=True)), ('updated_at', models.DateTimeField(auto_now=True)), ('expires_at', models.DateTimeField()), ('branch', models.ForeignKey(on_delete=models.deletion.CASCADE, related_name='pos_pairing_flows', to='companies.branch'))]),
        migrations.CreateModel(name='POSPinResetToken', fields=[('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)), ('created_at', models.DateTimeField(auto_now_add=True)), ('updated_at', models.DateTimeField(auto_now=True)), ('token_hash', models.CharField(max_length=256)), ('expires_at', models.DateTimeField()), ('consumed_at', models.DateTimeField(blank=True, null=True)), ('company', models.ForeignKey(on_delete=models.deletion.PROTECT, related_name='pos_pin_reset_tokens', to='companies.company')), ('created_by', models.ForeignKey(blank=True, null=True, on_delete=models.deletion.PROTECT, related_name='created_pos_pin_reset_tokens', to=settings.AUTH_USER_MODEL)), ('user', models.ForeignKey(on_delete=models.deletion.CASCADE, related_name='pos_pin_reset_tokens', to=settings.AUTH_USER_MODEL))]),
        migrations.CreateModel(name='POSOperatorSession', fields=[('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)), ('created_at', models.DateTimeField(auto_now_add=True)), ('updated_at', models.DateTimeField(auto_now=True)), ('token_hash', models.CharField(max_length=256)), ('expires_at', models.DateTimeField()), ('ended_at', models.DateTimeField(blank=True, null=True)), ('device', models.ForeignKey(on_delete=models.deletion.PROTECT, related_name='operator_sessions', to='pos.posdevice')), ('operator', models.ForeignKey(on_delete=models.deletion.PROTECT, related_name='pos_operator_sessions', to=settings.AUTH_USER_MODEL))]),
        migrations.CreateModel(name='POSOperatorPinAttempt', fields=[('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')), ('created_at', models.DateTimeField(auto_now_add=True)), ('updated_at', models.DateTimeField(auto_now=True)), ('failures', models.PositiveSmallIntegerField(default=0)), ('locked_until', models.DateTimeField(blank=True, null=True)), ('device', models.ForeignKey(on_delete=models.deletion.CASCADE, related_name='pin_attempts', to='pos.posdevice')), ('operator', models.ForeignKey(on_delete=models.deletion.CASCADE, related_name='pos_pin_attempts', to=settings.AUTH_USER_MODEL))]),
        migrations.CreateModel(name='BranchPOSSettings', fields=[('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')), ('created_at', models.DateTimeField(auto_now_add=True)), ('updated_at', models.DateTimeField(auto_now=True)), ('cash_binding_mode', models.CharField(choices=[('FIXED', 'Fixo'), ('FLEXIBLE', 'Flexivel')], default='FLEXIBLE', max_length=10)), ('receipt_printer', models.CharField(default='none', max_length=80)), ('sale_confirmation_print', models.BooleanField(default=False)), ('receipt_print_mode', models.CharField(choices=[('automatic', 'Automatico'), ('manual', 'Manual')], default='manual', max_length=10)), ('receipt_format', models.CharField(choices=[('detailed', 'Detalhado'), ('simplified', 'Simplificado')], default='detailed', max_length=12)), ('paper_width', models.PositiveSmallIntegerField(default=80, validators=[django.core.validators.MinValueValidator(40), django.core.validators.MaxValueValidator(120)])), ('copies', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])), ('local_report_print_preferences', models.JSONField(blank=True, default=dict)), ('sound_enabled', models.BooleanField(default=True)), ('screen_timeout_seconds', models.PositiveIntegerField(blank=True, null=True)), ('peripherals', models.JSONField(blank=True, default=dict)), ('branch', models.OneToOneField(on_delete=models.deletion.CASCADE, related_name='pos_settings', to='companies.branch')), ('default_cash_register', models.ForeignKey(blank=True, null=True, on_delete=models.deletion.SET_NULL, related_name='+', to='cash.cashregister'))]),
        migrations.CreateModel(name='POSDeviceSettings', fields=[('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')), ('created_at', models.DateTimeField(auto_now_add=True)), ('updated_at', models.DateTimeField(auto_now=True)), ('cash_binding_mode', models.CharField(blank=True, choices=[('FIXED', 'Fixo'), ('FLEXIBLE', 'Flexivel')], max_length=10)), ('receipt_printer', models.CharField(blank=True, max_length=80)), ('sale_confirmation_print', models.BooleanField(blank=True, null=True)), ('receipt_print_mode', models.CharField(blank=True, max_length=10)), ('receipt_format', models.CharField(blank=True, max_length=12)), ('paper_width', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(40), django.core.validators.MaxValueValidator(120)])), ('copies', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])), ('local_report_print_preferences', models.JSONField(blank=True, default=dict)), ('sound_enabled', models.BooleanField(blank=True, null=True)), ('screen_timeout_seconds', models.PositiveIntegerField(blank=True, null=True)), ('peripherals', models.JSONField(blank=True, default=dict)), ('default_cash_register', models.ForeignKey(blank=True, null=True, on_delete=models.deletion.SET_NULL, related_name='+', to='cash.cashregister')), ('device', models.OneToOneField(on_delete=models.deletion.CASCADE, related_name='settings', to='pos.posdevice'))]),
        migrations.CreateModel(name='AuthenticationChallenge', fields=[('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)), ('created_at', models.DateTimeField(auto_now_add=True)), ('updated_at', models.DateTimeField(auto_now=True)), ('purpose', models.CharField(choices=[('POS_DEVICE_PAIRING', 'Pareamento POS')], default='POS_DEVICE_PAIRING', max_length=40)), ('channel', models.CharField(max_length=20)), ('destination_fingerprint', models.CharField(max_length=64)), ('destination_masked', models.CharField(max_length=254)), ('code_hash', models.CharField(max_length=256)), ('expires_at', models.DateTimeField()), ('attempts', models.PositiveSmallIntegerField(default=0)), ('max_attempts', models.PositiveSmallIntegerField(default=5)), ('resend_count', models.PositiveSmallIntegerField(default=0)), ('consumed_at', models.DateTimeField(blank=True, null=True)), ('branch', models.ForeignKey(on_delete=models.deletion.PROTECT, related_name='authentication_challenges', to='companies.branch')), ('pairing_flow', models.ForeignKey(on_delete=models.deletion.CASCADE, related_name='challenges', to='pos.pairingflow'))]),
        migrations.AddConstraint(model_name='posoperatorpinattempt', constraint=models.UniqueConstraint(fields=('device', 'operator'), name='pos_pin_attempt_device_operator_unique')),
        migrations.AddIndex(model_name='posoperatorsession', index=models.Index(fields=['device', 'operator', 'expires_at'], name='pos_posoper_device__9187d6_idx')),
    ]
