# Generated by Django 6.1 on 2026-09-15 00:24

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cash', '0009_remove_legacy_withdrawal_effect_constraint'),
        ('companies', '0053_table_set_customer_permission'),
        ('pos', '0002_pos_performance_and_catalog_settings'),
        ('products', '0018_category_soft_delete_financial_overrides'),
        ('sales', '0025_saleitem_historical_promotion_snapshot'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuickSaleCheckout',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('open', 'Em edição'), ('paid', 'Pago'), ('finalized', 'Finalizado'), ('cancelled', 'Cancelado')], db_index=True, default='open', max_length=10)),
                ('discount_intent', models.JSONField(blank=True, default=dict)),
                ('service_fee_waived', models.BooleanField(default=False)),
                ('financial_snapshot', models.JSONField(blank=True, default=dict)),
                ('creation_idempotency_key', models.UUIDField(blank=True, editable=False, null=True)),
                ('creation_request_fingerprint', models.CharField(blank=True, default='', editable=False, max_length=64)),
                ('finalization_idempotency_key', models.UUIDField(blank=True, editable=False, null=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quick_sale_checkouts', to='companies.branch')),
                ('cash_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='quick_sale_checkouts', to='cash.cashsession')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quick_sale_checkouts', to='companies.company')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='quick_sale_checkouts', to='companies.customer')),
                ('discount_approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_quick_sale_discounts', to=settings.AUTH_USER_MODEL)),
                ('item_discount_approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_quick_sale_item_discounts', to=settings.AUTH_USER_MODEL)),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quick_sale_checkouts', to=settings.AUTH_USER_MODEL)),
                ('pos_device', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quick_sale_checkouts', to='pos.posdevice')),
                ('sale', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='quick_sale_checkout', to='sales.sale')),
                ('service_fee_waived_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_quick_sale_service_fee_waivers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-updated_at', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='QuickSaleCheckoutItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client_item_id', models.UUIDField()),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=14)),
                ('snapshot', models.JSONField(default=dict)),
                ('checkout', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='pos.quicksalecheckout')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quick_sale_checkout_items', to='products.product')),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='QuickSalePayment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('payment_method_name', models.CharField(max_length=100)),
                ('payment_method_code', models.CharField(max_length=50)),
                ('source_type', models.CharField(default='manual', editable=False, max_length=20)),
                ('status', models.CharField(choices=[('applied', 'Manual aplicado'), ('reversed', 'Estorno')], default='applied', max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('received_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('change_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('idempotency_key', models.UUIDField(editable=False)),
                ('request_fingerprint', models.CharField(editable=False, max_length=64)),
                ('reversal_reason', models.TextField(blank=True, default='')),
                ('cash_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='quick_sale_payments', to='cash.cashsession')),
                ('checkout', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='pos.quicksalecheckout')),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quick_sale_payments', to=settings.AUTH_USER_MODEL)),
                ('payment_method', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quick_sale_payments', to='sales.paymentmethod')),
                ('reversal_of', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reversal', to='pos.quicksalepayment')),
            ],
            options={
                'ordering': ('created_at', 'id'),
            },
        ),
        migrations.CreateModel(
            name='QuickSalePaymentAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('allocated_quantity', models.DecimalField(decimal_places=3, max_digits=14)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_allocations', to='pos.quicksalecheckoutitem')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='allocations', to='pos.quicksalepayment')),
            ],
        ),
        migrations.AddIndex(
            model_name='quicksalecheckout',
            index=models.Index(fields=['branch', 'operator', 'status'], name='pos_quicksa_branch__effeba_idx'),
        ),
        migrations.AddConstraint(
            model_name='quicksalecheckout',
            constraint=models.UniqueConstraint(fields=('pos_device', 'creation_idempotency_key'), name='pos_quick_sale_checkout_creation_idempotency_unique'),
        ),
        migrations.AddConstraint(
            model_name='quicksalecheckoutitem',
            constraint=models.UniqueConstraint(fields=('checkout', 'client_item_id'), name='pos_quick_sale_checkout_item_client_unique'),
        ),
        migrations.AddConstraint(
            model_name='quicksalecheckoutitem',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='pos_quick_sale_checkout_item_quantity_positive'),
        ),
        migrations.AddConstraint(
            model_name='quicksalepayment',
            constraint=models.UniqueConstraint(fields=('checkout', 'idempotency_key'), name='pos_quick_sale_payment_idempotency_unique'),
        ),
        migrations.AddConstraint(
            model_name='quicksalepayment',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='pos_quick_sale_payment_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='quicksalepaymentallocation',
            constraint=models.CheckConstraint(condition=models.Q(('allocated_quantity__gt', 0)), name='pos_quick_sale_allocation_quantity_positive'),
        ),
        migrations.AddConstraint(
            model_name='quicksalepaymentallocation',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='pos_quick_sale_allocation_amount_positive'),
        ),
    ]
