# Generated by Django 6.1 on 2026-09-15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0003_quick_sale_checkouts'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='quicksalecheckout',
            name='pos_quick_sale_checkout_creation_idempotency_unique',
        ),
        migrations.AddConstraint(
            model_name='quicksalecheckout',
            constraint=models.UniqueConstraint(
                fields=('pos_device', 'operator', 'creation_idempotency_key'),
                name='pos_quick_sale_checkout_creation_idempotency_unique',
            ),
        ),
    ]
