# Generated by Django 6.1 on 2026-09-28 19:57

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0056_document_printing_permissions'),
        ('pos', '0005_posdevice_active_cash_session'),
        ('sales', '0025_saleitem_historical_promotion_snapshot'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('active', 'Ativo'), ('inactive', 'Inativo')], default='active', max_length=10)),
                ('integration_type', models.CharField(choices=[('local_deep_link', 'Local deep link'), ('native_sdk', 'Native SDK'), ('server_api', 'Server API'), ('hybrid', 'Hybrid')], max_length=20)),
                ('capabilities', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ('name', 'id'),
            },
        ),
        migrations.CreateModel(
            name='PaymentProviderConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('environment', models.CharField(choices=[('sandbox', 'Sandbox'), ('production', 'Production')], max_length=12)),
                ('status', models.CharField(choices=[('active', 'Ativo'), ('inactive', 'Inativo')], default='active', max_length=10)),
                ('configuration', models.JSONField(blank=True, default=dict)),
                ('capabilities_override', models.JSONField(blank=True, default=dict)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payment_provider_connections', to='companies.branch')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_provider_connections', to='companies.company')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='connections', to='payment_integrations.paymentprovider')),
            ],
            options={
                'ordering': ('company_id', 'name', 'id'),
            },
        ),
        migrations.CreateModel(
            name='PaymentTerminal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('external_id', models.CharField(blank=True, default='', max_length=150)),
                ('status', models.CharField(choices=[('active', 'Ativo'), ('inactive', 'Inativo')], default='active', max_length=10)),
                ('capabilities', models.JSONField(blank=True, default=dict)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_terminals', to='companies.branch')),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='terminals', to='payment_integrations.paymentproviderconnection')),
                ('pos_device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payment_terminals', to='pos.posdevice')),
            ],
            options={
                'ordering': ('branch_id', 'name', 'id'),
            },
        ),
        migrations.CreateModel(
            name='PaymentIntent',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('origin_type', models.CharField(choices=[('quick_sale', 'Venda rápida'), ('table', 'Mesa'), ('command', 'Comanda')], max_length=20)),
                ('origin_id', models.CharField(max_length=80)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('status', models.CharField(choices=[('created', 'Criado'), ('ready', 'Pronto'), ('processing', 'Processando'), ('approved', 'Aprovado'), ('declined', 'Recusado'), ('cancelled', 'Cancelado'), ('error', 'Erro'), ('unknown', 'Desconhecido'), ('applied', 'Aplicado'), ('reversed', 'Estornado')], db_index=True, default='created', max_length=10)),
                ('idempotency_key', models.UUIDField(editable=False)),
                ('request_fingerprint', models.CharField(editable=False, max_length=64)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_intents', to='companies.branch')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_intents', to='companies.company')),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_intents', to=settings.AUTH_USER_MODEL)),
                ('payment_method', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_intents', to='sales.paymentmethod')),
                ('pos_device', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_intents', to='pos.posdevice')),
                ('provider_connection', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_intents', to='payment_integrations.paymentproviderconnection')),
                ('terminal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payment_intents', to='payment_integrations.paymentterminal')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='PaymentAttempt',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('attempt_number', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('created', 'Criada'), ('processing', 'Processando'), ('approved', 'Aprovada'), ('declined', 'Recusada'), ('cancelled', 'Cancelada'), ('error', 'Erro'), ('unknown', 'Desconhecido')], db_index=True, default='created', max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('provider_transaction_id', models.CharField(blank=True, default='', max_length=150)),
                ('provider_order_id', models.CharField(blank=True, default='', max_length=150)),
                ('provider_reference', models.CharField(blank=True, default='', max_length=150)),
                ('terminal_external_id', models.CharField(blank=True, default='', max_length=150)),
                ('authorization_code', models.CharField(blank=True, default='', max_length=100)),
                ('nsu', models.CharField(blank=True, default='', max_length=100)),
                ('card_brand', models.CharField(blank=True, default='', max_length=50)),
                ('card_mask', models.CharField(blank=True, default='', max_length=32)),
                ('installments', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('payment_product', models.CharField(blank=True, default='', max_length=50)),
                ('payment_product_detail', models.CharField(blank=True, default='', max_length=100)),
                ('provider_status', models.CharField(blank=True, default='', max_length=100)),
                ('provider_status_code', models.CharField(blank=True, default='', max_length=100)),
                ('provider_message', models.CharField(blank=True, default='', max_length=500)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('request_metadata', models.JSONField(blank=True, default=dict)),
                ('response_metadata', models.JSONField(blank=True, default=dict)),
                ('intent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attempts', to='payment_integrations.paymentintent')),
                ('provider_connection', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_attempts', to='payment_integrations.paymentproviderconnection')),
                ('terminal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payment_attempts', to='payment_integrations.paymentterminal')),
            ],
            options={
                'ordering': ('intent_id', 'attempt_number'),
            },
        ),
        migrations.AddIndex(
            model_name='paymentintent',
            index=models.Index(fields=['branch', 'status', 'created_at'], name='pay_intent_branch_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='paymentintent',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='payment_intent_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='paymentintent',
            constraint=models.UniqueConstraint(fields=('company', 'idempotency_key'), name='payment_intent_company_idempotency_unique'),
        ),
        migrations.AddIndex(
            model_name='paymentattempt',
            index=models.Index(fields=['intent', 'status', 'attempt_number'], name='pay_attempt_intent_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='paymentattempt',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='payment_attempt_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='paymentattempt',
            constraint=models.UniqueConstraint(fields=('intent', 'attempt_number'), name='payment_attempt_intent_number_unique'),
        ),
    ]
