# Generated by Django 6.1 on 2026-09-28

from django.db import migrations, models
from django.db.models import Q


class Migration(migrations.Migration):

    dependencies = [
        ('payment_integrations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentintent',
            name='application_context',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddConstraint(
            model_name='paymentintent',
            constraint=models.UniqueConstraint(
                condition=Q(
                    ('origin_type', 'quick_sale'),
                    ('status__in', ('created', 'ready', 'processing', 'declined', 'error', 'unknown', 'approved')),
                ),
                fields=('origin_id',),
                name='payment_intent_quick_sale_blocking_unique',
            ),
        ),
    ]
