# Generated by Django 6.1 on 2026-09-28

from django.db import migrations, models
from django.db.models import Q


class Migration(migrations.Migration):

    dependencies = [
        ('payment_integrations', '0002_paymentintent_application_context_and_quick_sale_constraint'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='paymentattempt',
            constraint=models.UniqueConstraint(
                condition=~Q(provider_transaction_id=''),
                fields=('provider_connection', 'provider_transaction_id'),
                name='payment_attempt_connection_transaction_unique',
            ),
        ),
    ]
