# Generated by Django 6.1 on 2026-08-15 20:29

import django.db.models.deletion
import django.db.models.functions.text
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0007_require_access_profile_remove_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('active', 'Ativo'), ('inactive', 'Inativo')], default='active', max_length=10)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_categories', to='companies.company')),
            ],
            options={
                'ordering': ('company__trade_name', 'name'),
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('internal_code', models.CharField(max_length=100)),
                ('barcode', models.CharField(blank=True, max_length=100)),
                ('unit', models.CharField(choices=[('un', 'Unidade'), ('kg', 'Quilograma'), ('g', 'Grama'), ('l', 'Litro'), ('ml', 'Mililitro')], default='un', max_length=5)),
                ('cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('sale_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('image', models.URLField(blank=True, max_length=500, null=True)),
                ('is_sellable', models.BooleanField(default=True)),
                ('inventory_behavior', models.CharField(choices=[('direct', 'Estoque proprio'), ('none', 'Sem estoque'), ('components', 'Baixa por componentes')], default='direct', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Ativo'), ('inactive', 'Inativo')], default='active', max_length=10)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='products', to='products.category')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='companies.company')),
            ],
            options={
                'ordering': ('company__trade_name', 'name'),
            },
        ),
        migrations.CreateModel(
            name='ProductComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12)),
                ('component_product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='used_as_component', to='products.product')),
                ('parent_product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='components', to='products.product')),
            ],
            options={
                'ordering': ('component_product__name',),
            },
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(models.F('company'), django.db.models.functions.text.Lower('name'), name='products_category_company_name_ci_unique'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(models.F('company'), django.db.models.functions.text.Lower('internal_code'), name='products_product_company_internal_code_ci_unique'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(models.F('company'), django.db.models.functions.text.Lower('barcode'), condition=models.Q(('barcode', ''), _negated=True), name='products_product_company_barcode_ci_unique'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(condition=models.Q(('cost__gte', 0)), name='products_product_cost_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(condition=models.Q(('sale_price__gte', 0)), name='products_product_sale_price_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='productcomponent',
            constraint=models.UniqueConstraint(fields=('parent_product', 'component_product'), name='products_component_pair_unique'),
        ),
        migrations.AddConstraint(
            model_name='productcomponent',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='products_component_quantity_positive'),
        ),
        migrations.AddConstraint(
            model_name='productcomponent',
            constraint=models.CheckConstraint(condition=models.Q(('parent_product', models.F('component_product')), _negated=True), name='products_component_not_self'),
        ),
    ]
