# Generated by Django 6.1 on 2026-08-16 22:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0016_sprint_11_5'),
        ('products', '0004_product_category_contract'),
    ]

    operations = [
        migrations.CreateModel(
            name='BranchProductPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sale_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_prices', to='companies.branch')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branch_prices', to='products.product')),
            ],
            options={
                'ordering': ('branch__name', 'product__name'),
                'constraints': [models.UniqueConstraint(fields=('product', 'branch'), name='products_branch_price_product_branch_unique'), models.CheckConstraint(condition=models.Q(('sale_price__gte', 0)), name='products_branch_price_nonnegative')],
            },
        ),
    ]
