# Generated by Django 6.1 on 2026-08-19 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_product_normalized_name_unique'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='inventory_behavior',
            field=models.CharField(choices=[('direct', 'Estoque próprio'), ('none', 'Sem estoque'), ('components', 'Baixa por componentes')], default='direct', max_length=20),
        ),
    ]
