# Generated by Django 6.1 on 2026-08-24 16:24

import django.db.models.deletion
import django.db.models.functions.text
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0032_v2_6_product_permissions'),
        ('products', '0008_v2_6_product_configuration'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModifierGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('is_required', models.BooleanField(default=False)),
                ('min_selections', models.PositiveIntegerField(default=0)),
                ('max_selections', models.PositiveIntegerField(blank=True, null=True)),
                ('allow_option_quantity', models.BooleanField(default=False)),
                ('sort_order', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('active', 'Ativo'), ('inactive', 'Inativo')], default='active', max_length=10)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='modifier_groups', to='companies.company')),
            ],
            options={
                'ordering': ('sort_order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='ModifierOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('option_type', models.CharField(choices=[('add', 'Adicionar'), ('remove', 'Remover'), ('observation', 'Observação')], default='add', max_length=12)),
                ('additional_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('sort_order', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('active', 'Ativo'), ('inactive', 'Inativo')], default='active', max_length=10)),
                ('modifier_group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='options', to='products.modifiergroup')),
            ],
            options={
                'ordering': ('sort_order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='ProductModifierGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('active', 'Ativo'), ('inactive', 'Inativo')], default='active', max_length=10)),
                ('modifier_group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_links', to='products.modifiergroup')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='modifier_groups', to='products.product')),
            ],
            options={
                'ordering': ('sort_order', 'id'),
            },
        ),
        migrations.AddConstraint(
            model_name='modifiergroup',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), condition=models.Q(('company_id__isnull', False)), name='products_modifier_group_company_name_ci_unique'),
        ),
        migrations.AddConstraint(
            model_name='modifieroption',
            constraint=models.CheckConstraint(condition=models.Q(('additional_price__gte', 0)), name='products_modifier_option_price_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='modifieroption',
            constraint=models.UniqueConstraint(fields=('modifier_group', 'name'), name='products_modifier_option_group_name_unique'),
        ),
        migrations.AddConstraint(
            model_name='productmodifiergroup',
            constraint=models.UniqueConstraint(fields=('product', 'modifier_group'), name='products_modifier_link_unique'),
        ),
    ]
