# Generated by Django 6.1 on 2026-08-29 20:53

import django.db.models.deletion
import django.db.models.functions.text
import django.db.models.manager
from django.conf import settings
from django.db import migrations, models
from django.db.models import Count
from django.db.models.functions import Lower
from django.utils import timezone


def migrate_inactive_modifiers(apps, schema_editor):
    ModifierGroup = apps.get_model('products', 'ModifierGroup')
    ModifierOption = apps.get_model('products', 'ModifierOption')
    ProductModifierGroup = apps.get_model('products', 'ProductModifierGroup')
    deleted_at = timezone.now()
    inactive_group_ids = list(
        ModifierGroup.objects.filter(status='inactive').values_list('pk', flat=True)
    )
    ModifierOption.objects.filter(
        models.Q(status='inactive') | models.Q(modifier_group_id__in=inactive_group_ids)
    ).update(status='inactive', deleted_at=deleted_at)
    ProductModifierGroup.objects.filter(
        models.Q(status='inactive') | models.Q(modifier_group_id__in=inactive_group_ids)
    ).update(status='inactive', deleted_at=deleted_at)
    ModifierGroup.objects.filter(pk__in=inactive_group_ids).update(
        status='inactive', deleted_at=deleted_at,
    )
    group_ids = ModifierOption.objects.filter(
        status='active', deleted_at__isnull=True,
    ).values_list('modifier_group_id', flat=True).distinct()
    for group_id in group_ids.iterator():
        used_names = set()
        options = ModifierOption.objects.filter(
            modifier_group_id=group_id,
            status='active',
            deleted_at__isnull=True,
        ).annotate(normalized_name=Lower('name')).order_by('pk')
        for option in options.iterator():
            normalized = option.normalized_name
            if normalized not in used_names:
                used_names.add(normalized)
                continue
            suffix = f' ({option.pk})'
            candidate = f'{option.name[:100 - len(suffix)]}{suffix}'
            counter = 2
            with schema_editor.connection.cursor() as cursor:
                cursor.execute('SELECT LOWER(%s)', [candidate])
                normalized_candidate = cursor.fetchone()[0]
            while normalized_candidate in used_names:
                suffix = f' ({option.pk}-{counter})'
                candidate = f'{option.name[:100 - len(suffix)]}{suffix}'
                counter += 1
                with schema_editor.connection.cursor() as cursor:
                    cursor.execute('SELECT LOWER(%s)', [candidate])
                    normalized_candidate = cursor.fetchone()[0]
            ModifierOption.objects.filter(pk=option.pk).update(name=candidate)
            used_names.add(normalized_candidate)


def ensure_legacy_constraints_can_be_restored(apps, schema_editor):
    ModifierGroup = apps.get_model('products', 'ModifierGroup')
    ModifierOption = apps.get_model('products', 'ModifierOption')
    ProductModifierGroup = apps.get_model('products', 'ProductModifierGroup')
    duplicate_group_names = ModifierGroup.objects.annotate(
        normalized_name=Lower('name')
    ).values('normalized_name').annotate(total=Count('pk')).filter(total__gt=1).exists()
    duplicate_option_names = ModifierOption.objects.values(
        'modifier_group_id', 'name'
    ).annotate(total=Count('pk')).filter(total__gt=1).exists()
    duplicate_links = ProductModifierGroup.objects.values(
        'product_id', 'modifier_group_id'
    ).annotate(total=Count('pk')).filter(total__gt=1).exists()
    if duplicate_group_names or duplicate_option_names or duplicate_links:
        raise RuntimeError(
            'Nao e possivel reverter o soft-delete de modificadores depois de reutilizar nomes ou vinculos.'
        )


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0042_branchsettings_table_range'),
        ('products', '0013_intelligent_modifier_stock_links'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='modifiergroup',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='modifieroption',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='productmodifiergroup',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='modifiergroup',
            name='products_modifier_group_company_name_ci_unique',
        ),
        migrations.RemoveConstraint(
            model_name='modifieroption',
            name='products_modifier_option_group_name_unique',
        ),
        migrations.RemoveConstraint(
            model_name='productmodifiergroup',
            name='products_modifier_link_unique',
        ),
        migrations.AddField(
            model_name='modifiergroup',
            name='deleted_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='modifiergroup',
            name='deleted_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='deleted_%(app_label)s_%(class)ss', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='modifieroption',
            name='deleted_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='modifieroption',
            name='deleted_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='deleted_%(app_label)s_%(class)ss', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='productmodifiergroup',
            name='deleted_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='productmodifiergroup',
            name='deleted_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='deleted_%(app_label)s_%(class)ss', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RunPython(
            migrate_inactive_modifiers,
            ensure_legacy_constraints_can_be_restored,
        ),
        migrations.AddConstraint(
            model_name='modifiergroup',
            constraint=models.UniqueConstraint(models.F('company'), django.db.models.functions.text.Lower('name'), condition=models.Q(('deleted_at__isnull', True)), name='products_modifier_group_company_name_ci_unique'),
        ),
        migrations.AddConstraint(
            model_name='modifiergroup',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('deleted_at__isnull', True), ('status', 'active')), models.Q(('deleted_at__isnull', False), ('status', 'inactive')), _connector='OR'), name='products_modifier_group_lifecycle_consistent'),
        ),
        migrations.AddConstraint(
            model_name='modifiergroup',
            constraint=models.CheckConstraint(condition=models.Q(('deleted_at__isnull', False), ('deleted_by__isnull', True), _connector='OR'), name='products_modifier_group_deleter_consistent'),
        ),
        migrations.AddConstraint(
            model_name='modifieroption',
            constraint=models.UniqueConstraint(models.F('modifier_group'), django.db.models.functions.text.Lower('name'), condition=models.Q(('deleted_at__isnull', True)), name='products_modifier_option_group_name_unique'),
        ),
        migrations.AddConstraint(
            model_name='modifieroption',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('deleted_at__isnull', True), ('status', 'active')), models.Q(('deleted_at__isnull', False), ('status', 'inactive')), _connector='OR'), name='products_modifier_option_lifecycle_consistent'),
        ),
        migrations.AddConstraint(
            model_name='modifieroption',
            constraint=models.CheckConstraint(condition=models.Q(('deleted_at__isnull', False), ('deleted_by__isnull', True), _connector='OR'), name='products_modifier_option_deleter_consistent'),
        ),
        migrations.AddConstraint(
            model_name='productmodifiergroup',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('product', 'modifier_group'), name='products_modifier_link_unique'),
        ),
        migrations.AddConstraint(
            model_name='productmodifiergroup',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('deleted_at__isnull', True), ('status', 'active')), models.Q(('deleted_at__isnull', False), ('status', 'inactive')), _connector='OR'), name='products_modifier_link_lifecycle_consistent'),
        ),
        migrations.AddConstraint(
            model_name='productmodifiergroup',
            constraint=models.CheckConstraint(condition=models.Q(('deleted_at__isnull', False), ('deleted_by__isnull', True), _connector='OR'), name='products_modifier_link_deleter_consistent'),
        ),
    ]
