# Generated by Django 6.1 on 2026-08-16 02:34

import django.db.models.expressions
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cash', '0002_classified_withdrawals'),
        ('companies', '0012_sprint_7_1_permissions'),
        ('sales', '0002_default_payment_methods'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='sale',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('operation_type', 'sale'), ('total', django.db.models.expressions.CombinedExpression(models.F('subtotal'), '-', models.F('discount')))), models.Q(('beneficiary_user__isnull', False), ('charged_amount__isnull', False), ('discount', 0), ('operation_type', 'consumption'), ('total', models.F('charged_amount'))), _connector='OR'), name='sales_sale_operation_amounts_coherent'),
        ),
        migrations.AddConstraint(
            model_name='sale',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('cancellation_reason__isnull', True), ('cancelled_at__isnull', True), ('cancelled_by__isnull', True), ('status', 'finalized')), models.Q(('cancellation_reason__isnull', False), ('cancelled_at__isnull', False), ('cancelled_by__isnull', False), ('status', 'cancelled')), _connector='OR'), name='sales_sale_cancellation_coherent'),
        ),
    ]
