# Generated by Django 6.1 on 2026-08-16 21:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0015_promotions_permissions'),
        ('products', '0004_product_category_contract'),
        ('sales', '0005_promotions'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromotionSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('weekday', models.SmallIntegerField(choices=[(0, 'Domingo'), (1, 'Segunda'), (2, 'Terca'), (3, 'Quarta'), (4, 'Quinta'), (5, 'Sexta'), (6, 'Sabado')])),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
            ],
            options={
                'ordering': ('weekday', 'start_time', 'id'),
            },
        ),
        migrations.RemoveConstraint(
            model_name='promotion',
            name='sales_promotion_period_valid',
        ),
        migrations.AddField(
            model_name='promotion',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='promotions', to='companies.branch'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='ends_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='promotion',
            constraint=models.CheckConstraint(condition=models.Q(('ends_at__isnull', True), ('starts_at__lt', models.F('ends_at')), _connector='OR'), name='sales_promotion_period_valid'),
        ),
        migrations.AddField(
            model_name='promotionschedule',
            name='promotion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='sales.promotion'),
        ),
        migrations.AddConstraint(
            model_name='promotionschedule',
            constraint=models.UniqueConstraint(fields=('promotion', 'weekday', 'start_time', 'end_time'), name='sales_promotion_schedule_interval_unique'),
        ),
        migrations.AddConstraint(
            model_name='promotionschedule',
            constraint=models.CheckConstraint(condition=models.Q(('start_time', models.F('end_time')), _negated=True), name='sales_promotion_schedule_interval_nonempty'),
        ),
    ]
