# Generated by Django 6.1 on 2026-08-16 22:57

import django.db.models.deletion
import django.db.models.expressions
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


def backfill_sellers(apps, schema_editor):
    Sale = apps.get_model('sales', 'Sale')
    Sale.objects.filter(operation_type='sale', seller_user__isnull=True).update(
        seller_user_id=models.F('created_by_id')
    )


class Migration(migrations.Migration):

    dependencies = [
        ('cash', '0002_classified_withdrawals'),
        ('companies', '0017_backfill_branch_settings'),
        ('sales', '0006_promotions_v2'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='sale',
            name='sales_sale_operation_amounts_coherent',
        ),
        migrations.AddField(
            model_name='sale',
            name='commission_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14),
        ),
        migrations.AddField(
            model_name='sale',
            name='commission_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5),
        ),
        migrations.AddField(
            model_name='sale',
            name='discount_approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_discount_sales', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sale',
            name='seller_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='seller_sales', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sale',
            name='service_fee_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14),
        ),
        migrations.AddField(
            model_name='sale',
            name='service_fee_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5),
        ),
        migrations.RunPython(backfill_sellers, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='sale',
            constraint=models.CheckConstraint(condition=models.Q(('service_fee_rate__gte', 0), ('service_fee_rate__lte', 100)), name='sales_sale_service_fee_rate_range'),
        ),
        migrations.AddConstraint(
            model_name='sale',
            constraint=models.CheckConstraint(condition=models.Q(('service_fee_amount__gte', 0)), name='sales_sale_service_fee_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='sale',
            constraint=models.CheckConstraint(condition=models.Q(('commission_rate__gte', 0), ('commission_rate__lte', 100)), name='sales_sale_commission_rate_range'),
        ),
        migrations.AddConstraint(
            model_name='sale',
            constraint=models.CheckConstraint(condition=models.Q(('commission_amount__gte', 0)), name='sales_sale_commission_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='sale',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('operation_type', 'sale'), ('seller_user__isnull', False), ('total', django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(models.F('subtotal'), '-', models.F('promotion_discount_total')), '-', models.F('discount')), '+', models.F('service_fee_amount')))), models.Q(('beneficiary_user__isnull', False), ('charged_amount__isnull', False), ('commission_amount', 0), ('commission_rate', 0), ('discount', 0), ('operation_type', 'consumption'), ('promotion_discount_total', 0), ('seller_user__isnull', True), ('service_fee_amount', 0), ('service_fee_rate', 0), ('total', models.F('charged_amount'))), _connector='OR'), name='sales_sale_operation_amounts_coherent'),
        ),
        migrations.AddConstraint(
            model_name='sale',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('discount', 0), ('discount_approved_by__isnull', True)), ('discount__gt', 0), _connector='OR'), name='sales_sale_discount_approval_coherent'),
        ),
    ]
