# Generated by Django 6.1 on 2026-08-17 02:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cash', '0003_result_effect'),
        ('companies', '0019_accessprofile_commission_rate_and_more'),
        ('sales', '0007_sprint_11_6'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='service_fee_waived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sale',
            name='service_fee_waived_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='waived_service_fee_sales', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='sale',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('service_fee_waived', False), ('service_fee_waived_by__isnull', True)), ('service_fee_waived', True), _connector='OR'), name='sales_sale_service_fee_waiver_coherent'),
        ),
    ]
