# Generated by Django 6.1 on 2026-08-19 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0011_scrub_unsafe_idempotency_fingerprints'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotionschedule',
            name='weekday',
            field=models.SmallIntegerField(choices=[(0, 'Domingo'), (1, 'Segunda'), (2, 'Terça'), (3, 'Quarta'), (4, 'Quinta'), (5, 'Sexta'), (6, 'Sábado')]),
        ),
        migrations.AlterField(
            model_name='sale',
            name='operation_type',
            field=models.CharField(choices=[('sale', 'Venda'), ('consumption', 'Consumação')], default='sale', max_length=20),
        ),
    ]
