# Generated by Django 6.1 on 2026-08-24 16:24

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0014_v2_6_channels_and_fee_eligibility'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleitem',
            name='base_unit_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=14),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='modifier_snapshot',
            field=models.JSONField(blank=True, default=list, editable=False),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='modifier_unit_total',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=14),
        ),
    ]
