# Generated by Django 6.1 on 2026-09-13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0024_table_payment_provenance'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='saleitem',
            name='sales_item_promotion_snapshot_coherent',
        ),
        migrations.AddConstraint(
            model_name='saleitem',
            constraint=models.CheckConstraint(
                condition=(
                    models.Q(
                        ('promotion__isnull', True),
                        ('promotion_benefit', 0),
                        ('promotion_discount_type__isnull', True),
                        ('promotion_discount_value__isnull', True),
                        ('promotion_name__isnull', True),
                    )
                    | models.Q(
                        ('promotion_discount_type__isnull', False),
                        ('promotion_discount_value__isnull', False),
                        ('promotion_name__isnull', False),
                    )
                ),
                name='sales_item_promotion_snapshot_coherent',
            ),
        ),
    ]
